### ISSUE TITLE
Error in dashboard

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1622]
I got this error message when accessing dashboard in local
![err](https://cloud.githubusercontent.com/assets/1289631/14340172/213b93ae-fcaf-11e5-90f9-4ff7faed93aa.png)

**Comment by ducdhm** [comment]
Error message
```
ERROR io.milton.cloud.server.web.templating.HtmlTemplateRenderer  - Template exception, enable TRACE level logging for the stack trace
TRACE io.milton.cloud.server.web.templating.HtmlTemplateRenderer  - Template exception stacktrace
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getConvertedRatePerc' in  class io.milton.cloud.server.apps.email.EmailApp$EmailStats threw exception java.lang.ArithmeticException: / by zero at rootorg.admin.loopbackdns.com:/theme/apps/email/emailDashboardPortlet.html[line 38, column 68]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:223)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:180)
	at io.milton.cloud.server.apps.email.EmailApp.renderPortlets(EmailApp.java:467)
	at io.milton.cloud.server.apps.ApplicationManager.renderPortlets(ApplicationManager.java:489)
	at io.milton.cloud.server.web.templating.PortletsDirective.render(PortletsDirective.java:68)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:106)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.VelocityContentDirective.render(VelocityContentDirective.java:65)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.lambda$renderHtml$61(HtmlTemplateRenderer.java:188)
	at io.milton.cloud.sec.UntrustedCodeManager.execute(UntrustedCodeManager.java:54)
	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.renderHtml(HtmlTemplateRenderer.java:185)
	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:189)
	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:110)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:42)
	at io.milton.cloud.server.apps.orgs.OrganisationFolder.sendContent(OrganisationFolder.java:199)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:89)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:220)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:84)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:191)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException: / by zero
	at io.milton.cloud.server.apps.email.EmailApp$EmailStats.getConvertedRatePerc(EmailApp.java:1873)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:142)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:539)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:198)
	... 53 more
```
