### ISSUE TITLE
Pipeline errors are not being logged to pipeline results

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1676]
For example:

INFO  io.milton.cloud.server.manager.GroupManager  - profile updated: name=58d674c9-7195-406c-92f9-19f4b5ea00f2 id=157195731
WARN  io.milton.vfs.db.Profile  - Profile not found: 29487a7e-d788-4aff-b57d-c1f61c9ed7f5 in org: O1422344030203
ERROR co.kademi.server.integration.Pipeline  - Exception thrown from pipeline
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not a valid email address: n/a
	at co.kademi.server.integration.providers.ProfileTableProvider.updateOrInsert(ProfileTableProvider.java:154)
	at co.kademi.server.integration.providers.ProfileTableProvider.updateOrInsert(ProfileTableProvider.java:44)
	at co.kademi.server.integration.impl.DatabaseUpdateStep.exec(DatabaseUpdateStep.java:113)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:112)
	at co.kademi.server.integration.impl.NextStep.exec(NextStep.java:33)
	at jdk.nashorn.internal.scripts.Script$Recompilation$208$\^eval\_.processUsers(<eval>:52)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:627)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:192)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:381)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:187)
	at co.kademi.server.integration.impl.JsRowStep.exec(JsRowStep.java:132)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:112)
	at co.kademi.server.integration.impl.CsvInput.exec(CsvInput.java:88)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:112)
	at co.kademi.server.integration.impl.TransactionStep.exec(TransactionStep.java:50)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:112)
	at co.kademi.server.integration.impl.RecordExecutionStep.exec(RecordExecutionStep.java:131)
	at co.kademi.server.integration.Pipeline.start(Pipeline.java:198)
	at com.fuselms.apps.integration.UploadPipelineProcessable.lambda$doProcess$443(UploadPipelineProcessable.java:142)
	at com.fuselms.apps.integration.UploadPipelineProcessable$$Lambda$60/1037385750.accept(Unknown Source)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:91)
	at com.fuselms.apps.integration.UploadPipelineProcessable.doProcess(UploadPipelineProcessable.java:120)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$673(LocalAsynchProcessor.java:302)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$59/702502973.accept(Unknown Source)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:91)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$674(LocalAsynchProcessor.java:301)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$58/1297662476.execute(Unknown Source)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Not a valid email address: n/a
	at io.milton.mail.MailboxAddress.parse(MailboxAddress.java:59)
	at io.milton.cloud.server.web.KademiSecurityManager.createProfile(KademiSecurityManager.java:140)
	at co.kademi.server.integration.providers.ProfileTableProvider.updateOrInsert(ProfileTableProvider.java:152)
	... 37 more

**Comment by tuzzmaniandevil** [comment]
It will now record exceptions if the pipeline is wrapped with a RecordExecutionStep
