### ISSUE TITLE
Error log message for portlet is not enough for debugging

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1819]
```
Exception executing portlet: portletProductsList from custom app: waterco-signup
```
Here is example for unclear error message

**Comment by bradmac** [comment]
Here is the stack trace from SSH:
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'hydroxypure.kademi-beta.co:/theme/apps/watercoSignup/portletProductsList.html'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:166)
	at io.milton.cloud.server.repoapps.ControllerMappingList.renderPortlet(ControllerMappingList.java:695)
	at io.milton.cloud.server.repoapps.RepositoryApp.renderPortlets(RepositoryApp.java:257)
	at io.milton.cloud.server.apps.ApplicationManager.renderPortlets(ApplicationManager.java:511)
	at io.milton.cloud.server.web.templating.PortletsDirective.render(PortletsDirective.java:68)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Block.render(Block.java:82)
