### ISSUE TITLE
Group signup does not work for Zoetis

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2242]
http://admin.zoetis.olhub.com/reporting/esGroupSignups?startDate=01%2F07%2F2016&finishDate=+31%2F07%2F2016

No data displaying.

**Comment by bradmac** [comment]
Seeing this in logs:

INFO  io.milton.cloud.server.manager.SearchManager  - Index signuplog-30746481 does not exist, so create all mappings
INFO  io.milton.cloud.server.manager.SearchManager  - Creating 1 mappings in index signuplog-30746481
ERROR org.hibernate.AssertionFailure  - HHH000099: an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: possible non-threadsafe access to the session
ERROR io.milton.http.StandardFilter  - exception sending content
org.hibernate.AssertionFailure: possible non-threadsafe access to the session
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:130)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1112)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1066)
	at org.hibernate.loader.Loader.loadSingleRow(Loader.java:404)
	at org.hibernate.internal.ScrollableResultsImpl.prepareCurrentRow(ScrollableResultsImpl.java:240)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:117)
	at io.milton.cloud.server.apps.signup.SignupLogAppIndexer.walkItems(SignupLogAppIndexer.java:54)
	at io.milton.cloud.server.manager.SearchManager.lambda$reindex$6(SearchManager.java:264)
	at io.milton.cloud.server.manager.SearchManager$$Lambda$113/2082294316.accept(Unknown Source)
	at io.milton.cloud.server.search.DefaultElasticSearchManager.bulk(DefaultElasticSearchManager.java:668)
	at io.milton.cloud.server.manager.SearchManager.reindex(SearchManager.java:263)
	at io.milton.cloud.server.apps.search.ManageOrgSearchFolder.processForm(ManageOrgSearchFolder.java:131)

**Comment by bradmac** [comment]
Possibly an issue in the version of hibernate used on olhub:

https://hibernate.atlassian.net/browse/HHH-6857

**Comment by bradmac** [comment]
Also, CSV export is not being sorted by date

**Comment by bradmac** [comment]
Sorting not working properly over a year of data due to scrolling. It seems that records are sorted within each tranche
