### ISSUE TITLE
Inadequate error handling when templates are not found

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2519]
When a page is rendered referencing a template which does not exist, there is only a 500 error page displayed, and no meaningful logs are generated on the logs page

Here i an example of a stack trace

```
WARN  org.hibernate.engine.internal.StatefulPersistenceContext  - HHH000179: Narrowing proxy to class io.milton.vfs.db.Organisation - this operation breaks ==
INFO  io.milton.cloud.server.web.KademiSecurityManager  - Authorisation declined for anonymous access
INFO  io.milton.cloud.server.web.KademiSecurityManager  - Required priviledge: READ_CONTENT was not found in assigned priviledge list of size: 0 for resource type=class com.fuselms.apps.blogs.BlogsFolder href=/blogs/
ERROR io.milton.http.http11.GetHandler  - Exception sending content for:/myfiles of resource type: io.milton.cloud.server.apps.myfiles.MyFilesPage
ERROR io.milton.http.StandardFilter  - exception sending content
java.lang.RuntimeException: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'acb-rewards.kademi.com.au:/theme/apps/myfiles/components/myFilesDirectoryIndexComponent.html'
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:230)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:84)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:196)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'acb-rewards.kademi.com.au:/theme/apps/myfiles/components/myFilesDirectoryIndexComponent.html'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:169)
	at io.milton.cloud.server.apps.ComponentBean.renderComponent(ComponentBean.java:171)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:119)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:127)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:47)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:231)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:114)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:42)
	at io.milton.cloud.server.web.TemplatedHtmlPage.sendContent(TemplatedHtmlPage.java:159)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:89)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:220)
	... 17 more
```

**Comment by bradmac** [comment]
We should
- handle template not found gracefully and display an informative message
- ensure that any exceptions from template rendering are captured to the logs index
