### ISSUE TITLE
Pipeline Scheduler: Add support for a day name

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2529]
Add support to be able to select specific days the schedule is allow to run on, i.e. Sunday to Saterday

Add to columns to PipelineSchedule
- String dayName
- Date scheduledEndDate

Note that the "endDate" property is currently used to determine the next time the schedule is executed. Ie "endDate" is the end date of the interval the schedule is being run for.

How this should work:

Have 2 end dates on the schedule
- Interval end date - Used to calculate the interval
- Schedule end date - Calculated from the interval end date then compared to the day names selected and find the next available day to run on.

When calculating the next run date, first find the normal endDate, and set it. And then calculate the first day matching the dayName if dayName is not null, and set that as the scheduledEndDate. The schedule should be run when the scheduledEndDate is reached, but it should use endDate as the interval enddate, eg for selecting records.

**Comment by gonzalon** [comment]
When Im trying to create a new Endpoint (Following: http://docs.kademi.co/programs/dev/d2/int1/pconfiguring-pipelines-with-xml.html)

I'm getting:

```com.thoughtworks.xstream.mapper.CannotResolveClassException: RecordExecutionStep
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:56)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:45)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:912)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:903)
	at com.fuselms.apps.integration.EndPointMappingCache.loadMappings(EndPointMappingCache.java:55)
	at com.fuselms.apps.integration.EndPointMappingCache.getMappings(EndPointMappingCache.java:44)
	at com.fuselms.apps.integration.ManageIntegrationPage.getEndPointMappings(ManageIntegrationPage.java:248)
	at com.fuselms.apps.integration.ManageIntegrationPage.sendContent(ManageIntegrationPage.java:114)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:220)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:84)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:185)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
ERROR io.milton.http.StandardFilter  - exception sending content
java.lang.RuntimeException: com.thoughtworks.xstream.mapper.CannotResolveClassException: RecordExecutionStep
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:230)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:84)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:185)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: RecordExecutionStep
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:56)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:45)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:912)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:903)
	at com.fuselms.apps.integration.EndPointMappingCache.loadMappings(EndPointMappingCache.java:55)
	at com.fuselms.apps.integration.EndPointMappingCache.getMappings(EndPointMappingCache.java:44)
	at com.fuselms.apps.integration.ManageIntegrationPage.getEndPointMappings(ManageIntegrationPage.java:248)
	at com.fuselms.apps.integration.ManageIntegrationPage.sendContent(ManageIntegrationPage.java:114)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:220)
	... 19 more```

**Comment by gonzalon** [comment]
Should we change the "Next Due" column whit the new field: scheduledEndDate in
http://localhost:8080/integration/#schedules-tab ???

**Comment by bradmac** [comment]
I think we should have a new column and display both

**Comment by gonzalon** [comment]
@bradmac its ready for test, I tested triggering the job and a with a scheduled one.

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
seem like both of Next Due and Scheduled Date has the same value with Start date although I choose Frequency is Month or week or Day

**Comment by hoanglinhlan** [comment]
and we should display Specific Day in the table

**Comment by gonzalon** [comment]
@hoanglinhlan its ok. it should be like that untill it gets processed. That happens on the "Scheduled end date".
You can put a date older than today and its going to get processed right away.

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
I cant see any your update

**Comment by gonzalon** [comment]
@hoanglinhlan  Im seeing the scheduled date being set right

https://lan-test.admin.kademi.com.au/integration/#schedules-tab

![image](https://cloud.githubusercontent.com/assets/2773216/26563820/a28f3256-44ae-11e7-93a4-0479941be3bc.png)
![image](https://cloud.githubusercontent.com/assets/2773216/26563822/abd7c1fc-44ae-11e7-8f5d-b8101fe7a654.png)

**Comment by hoanglinhlan** [comment]
passed
