### ISSUE TITLE
KSurvey to have JB fields for each survey question

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2587]
- Show a list of fields for each question in each survey
- Should support decisions based on survey responses.

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/2590

**Comment by bradmac** [comment]
You can now specify a function on the mappings which will load fields dynamically
```
controllerMappings.journeyFieldsFunction("loadSurveyFields");

function loadSurveyFields(rootFolder, fields) {
// get list of surveys and questions
fields.addTextJourneyField("q1", "Question 1", function() { 
 // callback to evaluate this field for a lead
            log.info ('callback function {}', arguments);
            log.info ('question name {}', q.name);

            var lead = arguments[0];
            var profileId = lead.profile.name;
            var surveyId = q.jsonObject.surveyId;
            log.info("getKsurveyFields: profileid={}", profileId);
            return getKsurveyFields(profileId, q.name, surveyId);
} );
}
```

**Comment by anhnt** [comment]
great it works

**Comment by anhnt** [comment]
I got following exception so that multi choices Fields dont work. @bradmac  can you please check it?

```
INFO  io.milton.cloud.server.repoapps.ControllerMappingList  - evaluate: function(){
                log.info ('callback function {}', arguments);
                log.info ('question name {}', q.name);

                var lead = arguments[0];
                var profileId = lead.profile.name;

                log.info("loadSurveyFields: profileid={}", profileId);
                return getKsurveyFields(profileId, q.name, surveyId, false);
            }
WARN  io.milton.cloud.server.repoapps.ControllerMappingList  - No such method: function(){
                log.info ('callback function {}', arguments);
                log.info ('question name {}', q.name);

                var lead = arguments[0];
                var profileId = lead.profile.name;

                log.info("loadSurveyFields: profileid={}", profileId);
                return getKsurveyFields(profileId, q.name, surveyId, false);
            }
java.lang.NoSuchMethodException: No such function function(){
                log.info ('callback function {}', arguments);
                log.info ('question name {}', q.name);

                var lead = arguments[0];
                var profileId = lead.profile.name;

                log.info("loadSurveyFields: profileid={}", profileId);
                return getKsurveyFields(profileId, q.name, surveyId, false);
            }
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:204)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.milton.cloud.server.repoapps.ControllerMappingList$RepoAppJourneyField.evaluate(ControllerMappingList.java:1847)
	at com.fuselms.apps.funnels.FunnelManager.findFieldValue(FunnelManager.java:782)
	at com.fuselms.apps.funnels.QueryBuilderExpression.findValue(QueryBuilderExpression.java:61)
	at com.fuselms.apps.funnels.QueryBuilderExpression.access$000(QueryBuilderExpression.java:32)
	at com.fuselms.apps.funnels.QueryBuilderExpression$Rule.evaluate(QueryBuilderExpression.java:395)
	at com.fuselms.apps.funnels.QueryBuilderExpression$Rules.evaluate(QueryBuilderExpression.java:309)
	at com.fuselms.apps.funnels.QueryBuilderExpression.evaluate(QueryBuilderExpression.java:52)
	at com.fuselms.apps.funnels.DecisionAction.onEnter(DecisionAction.java:104)
	at com.fuselms.apps.funnels.FunnelManager.nodeTransition(FunnelManager.java:598)
	at com.fuselms.apps.funnels.FunnelManager.createLead(FunnelManager.java:485)
	at com.fuselms.apps.funnels.FunnelManager.checkFunnel(FunnelManager.java:410)
	at com.fuselms.apps.funnels.FunnelManager.lambda$null$43(FunnelManager.java:365)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.fuselms.apps.funnels.FunnelManager.lambda$onFunnelEvent$44(FunnelManager.java:359)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:156)
	at com.fuselms.apps.funnels.FunnelManager.onFunnelEvent(FunnelManager.java:357)
	at io.milton.cloud.server.repoapps.ControllerMappingList$EventWrapper.goalAchieved(ControllerMappingList.java:1437)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1814$284AA$\^eval\_.submitSurvey(<eval>:111)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.milton.cloud.server.repoapps.ControllerResource.executeJs(ControllerResource.java:293)
	at io.milton.cloud.server.repoapps.ControllerResource.processForm(ControllerResource.java:144)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:196)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by anhnt** [comment]
Please check this line https://github.com/Kademi/kademi-server/blob/admin-theme-2/apps/ksurveyapp/APP-INF/app.js#L167

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/19954913/6b06eeb6-a1af-11e6-9e11-e11f51cd12ec.png)
KSurvey can now integrate to JB Fields completely. Above image is for multi choices, single choice and Yes/No question

**Comment by hoanglinhlan** [comment]
local test
passed

**Comment by anhnt** [comment]
As discussed, @hoanglinhlan please test and make sure JB decision choices work

**Comment by hoanglinhlan** [comment]
pass on my local
