### ISSUE TITLE
Comments component does not work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2735]
When using the comments component on the elearning page, with the stock bootstrap theme, posting a message does not work.I've hacked it by putting an ID on the textarea, but components should not rely on ID's

Also, currently the comments component depends on the initComments method which is part of the theme js file - init-theme.js. But components should be self contained, their app should inject any required js/css/less files through dependencies.

Also, the textarea is badly formatted, being all squished up.

** And please check the forums app front end pages. ***

**Comment by bradmac** [comment]
Is this fixed now?

**Comment by anhnt** [comment]
comment component works properly independently but when in forum question screen, user got error when replying a comment:

```
java.lang.ClassCastException: io.milton.cloud.server.db.ForumReply cannot be cast to io.milton.cloud.server.db.Comment
	at io.milton.cloud.server.db.Comment.get(Comment.java:82)
	at io.milton.cloud.server.apps.forums.CommentsResource.processForm(CommentsResource.java:171)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:89)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:185)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by bradmac** [comment]
@gonzalon please reproduce this issue in the forums app, by creating a forum, then posting a comment to it, then replying to that comment.

**Comment by gonzalon** [comment]
@bradmac I enabled the forum app, created a forum, but dunno how to comment / reply.
Don't see any options in "moderate posts". Could you help me with this?

**Comment by bradmac** [comment]
You need to access this from a front end website

**Comment by gonzalon** [comment]
@diegoperezn  could you review it please?

**Comment by hoanglinhlan** [comment]
passed
