### ISSUE TITLE
Cant create new promotion

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2872]
http://localhost:8080/rewards/
the system showing error message when I create a new promotion 
![image](https://cloud.githubusercontent.com/assets/20508726/22919731/026b7b54-f2c4-11e6-95e0-86ac3404740e.png)

**Comment by hoanglinhlan** [comment]
server log:
INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - next: Nothing more to send. Memory used=35% of 1820Mb
INFO  io.milton.http.HttpManager  - POST :: localhost:8080///rewards/ start
ERROR io.milton.http.StandardFilter  - exception sending content
java.lang.NoSuchMethodError: io.milton.cloud.util.Command.<init>(Ljava/lang/String;Ljava/util/function/Function;)V
	at com.fuselms.apps.rewards.ManageRewardsFolder.processForm(ManageRewardsFolder.java:61)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:83)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:195)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
WARN  io.milton.grizzly.GrizzlyMiltonResponse  - Failed to close outputstream after sendError
INFO  io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter  - Finished request: 14ms  for /rewards/ method=POST
INFO  io.milton.http.HttpManager  - POST :: localhost:8080///rewards/ finished 14ms, Status:HTTP/1.1 500, Length:null

**Comment by bradmac** [comment]
OK, thats nothing to do with the theme update, and its resolved in the main branch
