### ISSUE TITLE
Add quote enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3471]
1. Default the expiry date to the same as any other quotes added to the proposal
2. Improve the style of the file upload control
3. Timeago isnt being applied when quotes are added
4. Combine the "Back" button and lead info panel

1 & 2
![image](https://user-images.githubusercontent.com/826458/27559751-d19a4d24-5b15-11e7-9fa2-0de31dfe5997.png)

3)
![image](https://user-images.githubusercontent.com/826458/27559812-077b45d8-5b16-11e7-92ea-6ac0088d9af6.png)

4)
![image](https://user-images.githubusercontent.com/826458/27559842-1f1f0b7a-5b16-11e7-96a5-da157edf9bc1.png)

**Comment by anhnt** [comment]
All fixed in payment-lib 1.0.7

**Comment by anhnt** [comment]
Note that users can upload quote attachment in quote detail page, not quote initial creation form

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33372732-a02e3912-d531-11e7-94c6-c7c25ea8b443.png)

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , here from this page : http://version1.fresh11-fresh11.kademi-ci.co/quotes/
I can't open quote detail page , the edit button lead me to page error 500
What's wrong with me ?

admin : http://fresh11.admin.kademi-ci.co

**Comment by bradmac** [comment]
```
10:21:00 INFO  io.milton.http.HttpManager  - GET :: moblix-channel.kademi-ci.co/// finished 7ms, Status:HTTP/1.1 400, Length:null
10:21:01 INFO  KodeJS  - getLeadmanOrgSelector
10:21:01 INFO  KodeJS  - getPointsBalance
10:21:01 INFO  co.kademi.server.subscription.SubscriptionManager  - hasValidLicense :: Checking license: fromDate=19/12/2017,toDate=18/01/2018,planName=Trial - Thu Jan 18 00:00:00 NZDT 2018
10:21:01 INFO  io.milton.cloud.server.apps.user.UserApp  - Processing user visit event
10:21:01 INFO  io.milton.cloud.server.apps.calendar.ReminderProcessor  - doProcess
10:21:01 INFO  io.milton.cloud.server.db.EmailTrigger  - find triggers: eventId=userVisit
10:21:01 INFO  io.milton.cloud.server.db.EmailTrigger  - find: event=userVisit org=fresh11 list size=0 in time=2ms
10:21:01 INFO  io.milton.cloud.server.apps.email.EmailApp  - onEvent: TriggerEvent: class io.milton.cloud.server.apps.user.UserVisitEvent processed in 2ms
10:21:01 INFO  com.fuselms.apps.funnels.FunnelManager  - onFunnelEvent event=io.milton.cloud.server.apps.user.UserVisitEvent@3dec992b orgId=fresh11 adminDomain=fresh11 org.id=3428424
10:21:01 INFO  com.fuselms.apps.funnels.FunnelManager  - Completed onEvent in 2ms
10:21:01 ERROR co.kademi.server.stream.StreamManager  - Exception logging event to the stream: io.milton.cloud.server.event.ProfileIndexedItemUpdatedEvent@1cce380f because: null
10:21:01 java.lang.NullPointerException
10:21:01 	at co.kademi.server.stream.StreamManager$StreamEventListenever.onEvent(StreamManager.java:142)
10:21:01 	at io.milton.event.EventManagerImpl.fireEvent(EventManagerImpl.java:42)
10:21:01 	at io.milton.cloud.util.EventUtils.fireNoThrow(EventUtils.java:43)
10:21:01 	at io.milton.cloud.server.apps.user.UserApp$UserVisitProcessable.doProcess(UserApp.java:1504)
10:21:01 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$8(LocalAsynchProcessor.java:304)
10:21:01 	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
10:21:01 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:303)
10:21:01 	at io.milton.context.RootContext.execute(RootContext.java:90)
10:21:01 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
10:21:01 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
10:21:01 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
10:21:01 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:21:01 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:21:01 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:21:01 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:21:01 	at java.lang.Thread.run(Thread.java:748)
10:21:01 INFO  co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=377849472 updates=76 creates=0 loads=0
10:21:01 INFO  io.milton.cloud.server.manager.SearchManager  - Apply Deferred op: class io.milton.vfs.db.Profile 2
10:21:01 INFO  io.milton.cloud.server.manager.SearchManager  - updateIndexItem indexers=16 rootOrg=fresh11 updatedObject=io.milton.vfs.db.Profile@2a9
10:21:01 INFO  io.milton.http.http11.GetHandler  - processExistingResource: resource=com.fuselms.apps.payment.ManageQuotesFolder@43e6b6ac processed in 1441ms
10:21:01 INFO  io.milton.http.FilterChain  - Slow request 1916ms in filter io.milton.http.StandardFilter@6984f654 for path=/quotes/
10:21:01 INFO  io.milton.http.FilterChain  - Slow request 1916ms in filter co.kademi.server.subscription.KademiSubscriptionFilter@12bb46f8 for path=/quotes/
10:21:01 INFO  io.milton.http.FilterChain  - Slow request 1949ms in filter co.kademi.server.idp.IDPFilter@9696edb for path=/quotes/
10:21:01 INFO  io.milton.http.FilterChain  - Slow request 1955ms in filter io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter@42555237 for path=/quotes/
10:21:01 INFO  io.milton.http.HttpManager  - GET :: version1.fresh11-fresh11.kademi-ci.co///quotes/ finished 1955ms, Status:HTTP/1.1 200 OK, Length:10384
10:21:01 INFO  com.fuselms.apps.leadman.LeadManAppIndexer  - onUpdated: found leads to update: 0
10:21:01 INFO  io.milton.cloud.server.manager.SearchManager  - applyDeferredOps: row executed in 54 ms
10:21:01 INFO  io.milton.cloud.server.manager.SearchManager  - applyDeferredOps: all 1 executed in 59 ms
10:21:01 INFO  io.milton.cloud.server.repoapps.timers.JsScheduleService  - Found 0
10:21:01 INFO  io.milton.cloud.server.apps.email.EmailApp  - ScanTriggerTimersProcess: dueIds=0
10:21:01 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - SENDQUEUE Generation queue: 0 Presend queue: 0
10:21:01 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - _run: fetchsize=50 items=0
10:21:03 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - SENDQUEUE Generation queue: 0 Presend queue: 0
10:21:03 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - _run: fetchsize=50 items=0
10:21:05 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - SENDQUEUE Generation queue: 0 Presend queue: 0
10:21:05 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - _run: fetchsize=50 items=0
10:21:06 INFO  io.milton.http.HttpManager  - GET :: version1.fresh11-fresh11.kademi-ci.co///quotes/3504938/ start
10:21:06 INFO  co.kademi.server.subscription.SubscriptionManager  - hasValidLicense :: Checking license: fromDate=19/12/2017,toDate=18/01/2018,planName=Trial - Thu Jan 18 00:00:00 NZDT 2018
10:21:06 INFO  io.milton.cloud.server.apps.user.UserApp  - Time is not elapsed
10:21:06 WARN  io.milton.cloud.server.web.templating.VelocityHtmlTemplater  - Null or incompatible resource: null for source: fresh11-fresh11.kademi-ci.co:/theme/normal.html in resource factory: io.milton.cloud.server.web.KademiResourceFactory@759bcf36
10:21:06 ERROR io.milton.http.http11.GetHandler  - Exception sending content for:/quotes/3504938/ of resource type: com.fuselms.apps.payment.ManageQuoteFolder
10:21:06 org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'fresh11-fresh11.kademi-ci.co:/theme/normal.html'
10:21:06 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
10:21:06 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
10:21:06 	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1566)
10:21:06 	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1546)
10:21:06 	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
10:21:06 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.getTemplate(VelocityHtmlTemplater.java:245)
10:21:06 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:183)
10:21:06 	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:48)
10:21:06 	at com.fuselms.apps.payment.ManageQuoteFolder.sendContent(ManageQuoteFolder.java:419)
10:21:06 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
10:21:06 	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
10:21:06 	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
10:21:06 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
10:21:06 	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
10:21:06 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
10:21:06 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
10:21:06 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
10:21:06 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
10:21:06 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
10:21:06 	at io.milton.context.RootContext.execute(RootContext.java:90)
10:21:06 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at io.milton.http.HttpManager.process(HttpManager.java:158)
10:21:06 	at co.kademi.server.Kademi$1.service(Kademi.java:187)
10:21:06 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
10:21:06 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
10:21:06 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
10:21:06 	at java.lang.Thread.run(Thread.java:748)
10:21:06 ERROR io.milton.http.StandardFilter  - exception sending content
10:21:06 java.lang.RuntimeException: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'fresh11-fresh11.kademi-ci.co:/theme/normal.html'
10:21:06 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:233)
10:21:06 	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
10:21:06 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
10:21:06 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
10:21:06 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
10:21:06 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
10:21:06 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
10:21:06 	at io.milton.context.RootContext.execute(RootContext.java:90)
10:21:06 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
10:21:06 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:06 	at io.milton.http.HttpManager.process(HttpManager.java:158)
10:21:06 	at co.kademi.server.Kademi$1.service(Kademi.java:187)
10:21:06 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
10:21:06 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
10:21:06 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
10:21:06 	at java.lang.Thread.run(Thread.java:748)
10:21:06 Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'fresh11-fresh11.kademi-ci.co:/theme/normal.html'
10:21:06 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
10:21:06 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
10:21:06 	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1566)
10:21:06 	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1546)
10:21:06 	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
10:21:06 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.getTemplate(VelocityHtmlTemplater.java:245)
10:21:06 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:183)
10:21:06 	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:48)
10:21:06 	at com.fuselms.apps.payment.ManageQuoteFolder.sendContent(ManageQuoteFolder.java:419)
10:21:06 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
10:21:06 	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
10:21:06 	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
10:21:06 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
10:21:06 	... 21 more
```

**Comment by bradmac** [comment]
```
10:21:06 ERROR io.milton.http.http11.GetHandler  - Exception sending content for:/quotes/3504938/ of resource type: com.fuselms.apps.payment.ManageQuoteFolder
10:21:06 org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'fresh11-fresh11.kademi-ci.co:/theme/normal.html'
```

**Comment by bradmac** [comment]
So looks like the template for the edit quote page hasnt been updated for component themes

**Comment by anhnt** [comment]
@mkhoudary please have a look at java code. thanks

**Comment by bradmac** [comment]
@gonzalon can you assist please?

**Comment by gonzalon** [comment]
@AlaaKhalaf94 should be working fine now :)

**Comment by AlaaKhalaf94** [comment]
@gonzalon , look here please : http://version1.fresh16-fresh16.kademi-ci.co/quotes/3668719/
in "Quote Attachments" section
admin : http://fresh16.admin.kademi-ci.co/

- I can't remove any of attachment that I've added
- I add 2 type of attachment , img and csv file
when I click on img will open it in new tab , but when I click on csv file will open it as a text in new tab

![capture1](https://user-images.githubusercontent.com/26510030/34380959-09eedc98-eb0e-11e7-8580-a30784d95603.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94  Added the option to delete the attachments.
The links are working for me but anyways I talked with Brad about this and isn't that important at the moment!


![image](https://user-images.githubusercontent.com/2773216/34397266-927a42f2-ebd9-11e7-99ce-18c987a4e305.png)

**Comment by AlaaKhalaf94** [comment]
passed
