### ISSUE TITLE
orglocator app get 500 error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3553]
Please see stack trace

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at io.milton.cloud.server.apps.orglocator.OrgMapData.toBean(OrgMapData.java:58)
	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.searchQuery(OrgsMapPage.java:206)
	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.sendContent(OrgsMapPage.java:93)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:189)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:120)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
ERROR io.milton.http.StandardFilter  - exception sending content
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:233)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:189)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:120)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at io.milton.cloud.server.apps.orglocator.OrgMapData.toBean(OrgMapData.java:58)
	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.searchQuery(OrgsMapPage.java:206)
	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.sendContent(OrgsMapPage.java:93)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
	... 19 more
```

**Comment by anhnt** [comment]
here is the url: ```/orgsLocator/?maxResults=1000&jsonQuery=&orgTypes=```

**Comment by gonzalon** [comment]
Tested here: http://gnz.admin.kademi-prod.com/

Seems to work ok now :+1: 

http://version1.orglocatortest.kademi-prod.com/orgsLocator/?maxResults=1000&jsonQuery=&orgTypes=test-org-type
