### ISSUE TITLE
KSurveyApp is unable to open survey for editing

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3623]
When I try to open a survey for editing in the admin console, the ksurvey app returns a blank page, there's an exception as well:

```
ERROR io.milton.cloud.server.repoapps.ControllerMappingList  - TypeError: Can not invoke method [jdk.internal.dynalink.beans.OverloadedDynamicMethod
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object[])
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Throwable)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object[])
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Throwable)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String)
] with the passed arguments; they do not match any of its method signatures. in <eval> at line number 419
javax.script.ScriptException: TypeError: Can not invoke method [jdk.internal.dynalink.beans.OverloadedDynamicMethod
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object[])
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Throwable)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object[])
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Throwable)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String)
] with the passed arguments; they do not match any of its method signatures. in <eval> at line number 419
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.milton.cloud.server.repoapps.ControllerMappingList.executeJs(ControllerMappingList.java:991)
	at io.milton.cloud.server.repoapps.ControllerMappingList.processResolvers(ControllerMappingList.java:1011)
	at io.milton.cloud.server.repoapps.RepositoryApp.getAdminResourceByPath(RepositoryApp.java:337)
	at io.milton.cloud.server.web.KademiResourceFactory.findResource(KademiResourceFactory.java:239)
	at io.milton.cloud.server.web.KademiResourceFactory.getResource(KademiResourceFactory.java:172)
	at io.milton.http.MultipleResourceFactory.findFromFactories(MultipleResourceFactory.java:96)
	at io.milton.http.MultipleResourceFactory.getResource(MultipleResourceFactory.java:55)
	at io.milton.cloud.server.web.alt.AltFormatResourceFactory.getResource(AltFormatResourceFactory.java:134)
	at io.milton.http.MultipleResourceFactory.findFromFactories(MultipleResourceFactory.java:96)
	at io.milton.http.MultipleResourceFactory.getResource(MultipleResourceFactory.java:55)
	at io.milton.http.json.JsonResourceFactory.getResource(JsonResourceFactory.java:97)
	at io.milton.http.WellKnownResourceFactory.getResource(WellKnownResourceFactory.java:90)
	at io.milton.http.fck.FckResourceFactory.getResource(FckResourceFactory.java:55)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:90)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:419 TypeError: Can not invoke method [jdk.internal.dynalink.beans.OverloadedDynamicMethod
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Object[])
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String,Throwable)
 void org.slf4j.helpers.MarkerIgnoringBase.info(Marker,String)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Object[])
 void org.slf4j.impl.Log4jLoggerAdapter.info(String,Throwable)
 void org.slf4j.impl.Log4jLoggerAdapter.info(String)
] with the passed arguments; they do not match any of its method signatures.
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:103)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:73)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1289$14536AAAA$\^eval\_.findSurvey(<eval>:419)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 30 more
```

**Comment by mkhoudary** [comment]
Fixed that.. js engine couldn't find log.info(String, Object ...) signature when it was invoked this way:
`log.info('findSurvey > {} {} {} {}', rf, groupName, groupVal, mapOfGroups);`

When I changed it to be this way:
`log.info('findSurvey > {} {} {} {}', [rf, groupName, groupVal, mapOfGroups]);`

It worked normally.. 

@bradmac this is strange as Anh advised that this was always working..

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
I can not make preview to Survey , it shows me an error

Error rendering component: ksurveyForm
class org.apache.velocity.exception.MethodInvocationException - Invocation of method 'call' in class io.milton.cloud.server.repoapps.RepositoryApp threw exception ParsingException[The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored] at alaatest03.kademi-prod.com:/theme/apps/ksurveyapp/ksurveyFormComponent.html[line 22, column 26]

I test here : http://alaa-test.admin.kademi-prod.com/ksurvey/survey-2bf03299-b7c2-4a25-9d07-457c468d377c/#detail-tab

**Comment by mkhoudary** [comment]
@bradmac can you please check my solution?

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please review?
