### ISSUE TITLE
ES5 error generating timeline items from logs index

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3640]
```
Fielddata is disabled on text fields by default. Set fielddata=true on [userAgent] in order to load fielddata in memory

	at io.milton.cloud.server.apps.admin.ManageUserPage.lambda$getTimelineItems$94(ManageUserPage.java:1067)
	at io.milton.cloud.server.db.utils.LazyValueHolder2.get(LazyValueHolder2.java:39)
	at io.milton.cloud.server.apps.admin.ManageUserPage.getTimelineItems(ManageUserPage.java:1059)
```

**Comment by bradmac** [comment]
```
    "userAgent":     {
        "type": "text",
        "fields": {"keyword":         {
            "type": "keyword",
            "ignore_above": 256
        }}
    },
```

**Comment by bradmac** [comment]
After reindexing is like this
```
    "userAgent":     {
        "type": "keyword",
        "store": true,
        "eager_global_ordinals": true,
        "fields": {"text":         {
            "type": "text",
            "store": true,
            "fielddata": true
        }}
    },
```

**Comment by bradmac** [comment]
So looks like the problem is that when creating a new account, the logs index is created but with default mappings

**Comment by tuzzmaniandevil** [comment]
It seems to create the correct mappings, I starting my local (clean build) and mappings were correct, I then created a new sub account and it still created all the correct mappings for logs
