### ISSUE TITLE
Is not possible to delete the organization

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3646]
From here , http://kademi-prod.com/organisations/
I try delete this org id "myrewardstore001" , and this shows me this message

![capture1](https://user-images.githubusercontent.com/26510030/28610343-af3440e0-71f0-11e7-9a7e-a05dcb409e0c.PNG)

**Comment by ducdhm** [comment]
Error message in log
```
08:57:44 ERROR io.milton.http.StandardFilter  - exception sending content
08:57:44 java.lang.RuntimeException: Cannot delete an admin domain. Remove the admin domain first
08:57:44 	at io.milton.vfs.db.Organisation.softDelete(Organisation.java:822)
08:57:44 	at io.milton.cloud.server.apps.orgs.OrganisationFolder.delete(OrganisationFolder.java:158)
08:57:44 	at io.milton.http.DeleteHelperImpl.delete(DeleteHelperImpl.java:97)
08:57:44 	at io.milton.http.http11.DeleteHandler.processExistingResource(DeleteHandler.java:98)
08:57:44 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
08:57:44 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:131)
08:57:44 	at io.milton.http.http11.DeleteHandler.processResource(DeleteHandler.java:83)
08:57:44 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
08:57:44 	at io.milton.http.http11.DeleteHandler.process(DeleteHandler.java:72)
08:57:44 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
08:57:44 	at io.milton.http.FilterChain.process(FilterChain.java:46)
08:57:44 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
08:57:44 	at io.milton.http.FilterChain.process(FilterChain.java:46)
08:57:44 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
08:57:44 	at io.milton.context.RootContext.execute(RootContext.java:90)
08:57:44 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
08:57:44 	at io.milton.http.FilterChain.process(FilterChain.java:46)
08:57:44 	at io.milton.http.HttpManager.process(HttpManager.java:158)
08:57:44 	at co.kademi.server.Kademi$1.service(Kademi.java:186)
08:57:44 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
08:57:44 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
08:57:44 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
08:57:44 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ducdhm** [comment]
@bradmac can you return `Cannot delete an admin domain. Remove the admin domain first` error message to client for me to show ?
