### ISSUE TITLE
Configurable option to allow associate between points and debits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3728]

**Comment by bradmac** [comment]
@tuzzmaniandevil i think backend is mostly done, but we need the option in settings, and to make sure it works

**Comment by bradmac** [comment]
@tuzzmaniandevil please integrate with points expiry processor

**Comment by Uafinder** [comment]
Not sure which effect i should observe...

I've create bucket and debit two products with auto-reconcile, and two without.
Those with reconcile can't be removed.
![image](https://user-images.githubusercontent.com/1945230/31442876-725e7d42-aea0-11e7-801c-c377a58b1580.png)
http://vlad-test13.admin.kademi-ci.co/points-buckets/vlad13-points-points

**Comment by bradmac** [comment]
```
09:01:10 java.lang.RuntimeException: Exception executing com.fuselms.apps.rewardstore.ManagePointsSystemFolder$$Lambda$1239/1249316419@7dec044c
09:01:10 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:187)
09:01:10 	at com.fuselms.apps.rewardstore.ManagePointsSystemFolder.processForm(ManagePointsSystemFolder.java:130)
09:01:10 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
09:01:10 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
09:01:10 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
09:01:10 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
09:01:10 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
09:01:10 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
09:01:10 	at io.milton.http.FilterChain.process(FilterChain.java:46)
09:01:10 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:32)
09:01:10 	at io.milton.http.FilterChain.process(FilterChain.java:46)
09:01:10 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
09:01:10 	at io.milton.http.FilterChain.process(FilterChain.java:46)
09:01:10 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
09:01:10 	at io.milton.context.RootContext.execute(RootContext.java:90)
09:01:10 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
09:01:10 	at io.milton.http.FilterChain.process(FilterChain.java:46)
09:01:10 	at io.milton.http.HttpManager.process(HttpManager.java:158)
09:01:10 	at co.kademi.server.Kademi$1.service(Kademi.java:186)
09:01:10 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
09:01:10 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
09:01:10 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
09:01:10 	at java.lang.Thread.run(Thread.java:748)
09:01:10 Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
09:01:10 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
09:01:10 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
09:01:10 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
09:01:10 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
09:01:10 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
09:01:10 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58)
09:01:10 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3355)
09:01:10 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
09:01:10 	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
09:01:10 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
09:01:10 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
09:01:10 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
09:01:10 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
09:01:10 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
09:01:10 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
09:01:10 	at com.fuselms.apps.rewardstore.ManagePointsSystemFolder.removeDebits(ManagePointsSystemFolder.java:249)
09:01:10 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:209)
09:01:10 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:176)
09:01:10 	... 22 more
09:01:10 Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "points_debit" violates foreign key constraint "fk_15fub3ul8nxvoac32pp9q9wpk" on table "points_debit_link"
09:01:10   Detail: Key (id)=(625890) is still referenced from table "points_debit_link".
09:01:10 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
```

**Comment by tuzzmaniandevil** [comment]
With points, We don't allow a user to delete points if it's linked to a debit, It's will show an error
With Points Debits it will automatically delete the link

**Comment by Uafinder** [comment]
I was successfully able to delete points from here:
![image](https://user-images.githubusercontent.com/1945230/31820701-345b17aa-b5ab-11e7-8df3-fd1d0c6e3348.png)
![image](https://user-images.githubusercontent.com/1945230/31820740-52c8c390-b5ab-11e7-8da5-015b526e59bc.png)
Both auto-reconciled
http://vlad-test23.admin.kademi-ci.co/points-buckets/points/
http://vlad-test23.admin.kademi-ci.co/points-buckets/vlad23-points-points/?startDate=14%2F10%2F2017&finishDate=20%2F10%2F2017&dataQuery=&startPos=0#debits-tab

So probably that's not right

**Comment by tuzzmaniandevil** [comment]
@Uafinder That looks fine, You should be able to delete debits, It's only Points that are linked to debits you shouldn't be able to delete

**Comment by Uafinder** [comment]
Check please,
I've a bucket with Auto Reconcile enabled.
I've points awarded.
I've debit points by purchase via frontend and via debit points both.
And I've able to delete both points and debits and no errors appears.
Where i'm wrong?
http://vlad-test30.admin.kademi-ci.co/points-buckets/vlad30-store-points/?startDate=27%2F10%2F2017&finishDate=02%2F11%2F2017&dataQuery=&startPos=0#details-tab
http://vlad-test30.admin.kademi-ci.co/points-buckets/points/

**Comment by tuzzmaniandevil** [comment]
Checked. I can't delete points until I delete the debit records that are linked to it.

Were you deleting the debits first then the points? You should try just deleting the points and not the debits, You will get an error like this:

![image](https://user-images.githubusercontent.com/3378330/32636437-b1eed066-c619-11e7-8a3f-d181a27175de.png)

**Comment by Uafinder** [comment]
I wrote a video where I was succeed with deletion points which was linked to debits:
https://drive.google.com/open?id=19r1mKKNanWtk0Pj9KWGzJcg0BeDEH56s
I was do same thing as you on the screenshot
http://vladtest02.admin.kademi-ci.co/points-buckets/vlad02store-points/#details-tab

**Comment by tuzzmaniandevil** [comment]
I watched the video, The you just added points and deleted them again. You need to actually some at least part of the points record for it to be linked to a debit record.

**Comment by Uafinder** [comment]
Got it finally...
Yup, it works as expected!
