### ISSUE TITLE
Add ordering parameters to ecom store, like we have in reward store

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3791]
The reward store does a check on products when added to the cart to see if they have ordering fields, and if so the user is prompted to enter them

We need the same capability added to the ecom store.

**Comment by anhnt** [comment]
added js but i got errror when submit order form

![image](https://user-images.githubusercontent.com/735555/29908945-e6665cb4-8e4d-11e7-938e-aa1df68be02a.png)


Stack trace

```
java.lang.NullPointerException
	at com.fuselms.apps.shoppingcart.ShoppingCartResource.isValidStockConfig(ShoppingCartResource.java:460)
	at com.fuselms.apps.shoppingcart.ShoppingCartResource.processForm(ShoppingCartResource.java:281)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:28)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by anhnt** [comment]
Ok i fixed it by change form action to be ```/storeCheckout```
