### ISSUE TITLE
Allows anon users to follow a comment via email

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4003]
Currently when post a comment as anon user, i got this error:

Sorry, you need to be logged in to follow a post.

**Comment by bradmac** [comment]
Currently @anhnt is sending the newComment and follow params in a single request. This isnt working correctly because the server processes them seperately, and follow comes first:
```
            jsonResult = SessionManagerUtils.processFormCommandInTransaction(this, parameters, files,
                    new Command("follow", this::doFollow),
                    new Command("unfollow", this::doUnfollow),
                    new Command("newComment", this::doNewComment)
            );
```

**Comment by bradmac** [comment]
So we just need to move newComment up

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
How can i test it on QA?

**Comment by bradmac** [comment]
@Uafinder please chat with @anhnt to setup a test with comments

**Comment by anhnt** [comment]
We need to update jquery.comment.js to add the "following a comment via email" checkbox

**Comment by anhnt** [comment]
I got NPE 

```
java.lang.RuntimeException: Exception executing io.milton.cloud.server.apps.forums.CommentsResource$$Lambda$1659/885783936@45c0c7d1
	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:187)
	at io.milton.cloud.server.apps.forums.CommentsResource.processForm(CommentsResource.java:100)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:32)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:42)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at co.kademi.server.KademiWebsocketApplication.isUserConnected(KademiWebsocketApplication.java:171)
	at io.milton.cloud.server.apps.forums.NotificationsService.sendNotification(NotificationsService.java:95)
	at io.milton.cloud.server.manager.CommentService.newComment(CommentService.java:365)
	at io.milton.cloud.server.manager.CommentService.newComment(CommentService.java:298)
	at io.milton.cloud.server.apps.forums.CommentsResource.doNewComment(CommentsResource.java:188)
	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:209)
	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:176)
	... 22 more
```

I will set up an account on CI to reproduce

**Comment by bradmac** [comment]
i think the target profile is null
```
    public boolean isUserConnected(Profile target, String type, Object id) {
        List<KademiWebsocket> wsList = getSessions().get(type);
        if ( wsList == null || wsList.isEmpty() ) {
            return false;
        }

        for (KademiWebsocket ws : wsList) {
            if ( ws != null && ws.getItemId() != null && ws.getItemId().equals(id) && target.getId() == ws.getProfileId() ) {
                return true;
            }
        }
        return false;
    }
```

**Comment by tuzzmaniandevil** [comment]
Added a null check

**Comment by tuzzmaniandevil** [comment]
Also added anonymous profile tracking to websockets, This requires the Tracking app to be enabled

**Comment by anhnt** [comment]
looking good now. Over to @Uafinder for testing

**Comment by Uafinder** [comment]
Probably should be same button labels and color: Post

**Comment by Uafinder** [comment]
I've followed this instructions
1. So you need to setup a website with forums app enabled.
2. Create a group called "public" lowercase sensitive
3. add that group to your website setting: group access
4. add forum-user role to that group
so now edit index.html and drag comment component

But I see doubling for this component on prod
![image](https://user-images.githubusercontent.com/1945230/33264311-b0375018-d375-11e7-8bed-dab50a55eaf5.png)
Please assist
http://vlad-live.admin.kademi.com.au/pages/vladlive-forums/version1/

**Comment by anhnt** [comment]
@Uafinder we have already had that comment component for page template http://vladlive-forums_vlad-live.kademi.com.au//theme/contenteditor?fileName=page.html

So no need to add another one :)

**Comment by anhnt** [comment]
>Probably should be same button labels and color: Post
Fixed

**Comment by Uafinder** [comment]
Error when posting an anonymous comment
![image](https://user-images.githubusercontent.com/1945230/33318736-64334c38-d444-11e7-9744-b113792a0d0d.png)
http://version1.vlad62-forums_vlad-test62.kademi-ci.co/anon.html
http://vlad-test62.admin.kademi-ci.co/pages/vlad62-forums/version1/

**Comment by bradmac** [comment]
@tuzzmaniandevil this might be related to websockets on the CI server

**Comment by tuzzmaniandevil** [comment]
Fixed the WS

**Comment by Uafinder** [comment]
Still no posting for anonymous user
![image](https://user-images.githubusercontent.com/1945230/33433585-c7167194-d5e4-11e7-8965-e12232927c04.png)
http://version1.vlad65-anon_vlad-test65.kademi-ci.co/anon.html
http://vlad-test65.admin.kademi-ci.co/pages/vlad65-anon/version1/

**Comment by tuzzmaniandevil** [comment]
Allow anonymous comments is disabled:
![image](https://user-images.githubusercontent.com/3378330/33454193-fb46089c-d67c-11e7-8476-2da8a1dc5d2e.png)

**Comment by Uafinder** [comment]
oooops
All works ok, but email is not sending
![image](https://user-images.githubusercontent.com/1945230/33486969-7f9e2214-d6b4-11e7-9fc1-1e4255f31cab.png)
This is an issue described here:
https://github.com/Kademi/kademi-dev/issues/4328

**Comment by tuzzmaniandevil** [comment]
Issue #4328 is fixed so all good for you to re-test

**Comment by Uafinder** [comment]
It wasn't fixed, it was just close...

**Comment by bradmac** [comment]
@Uafinder please use a website name without hyphens, eg vlad65anon instead of vlad65-anon

**Comment by Uafinder** [comment]
Doesn't help...
http://vladtest01.admin.kademi-ci.co
![image](https://user-images.githubusercontent.com/1945230/33705559-6edc4936-db39-11e7-88a6-de6ec4089ca2.png)
http://vladtest01.admin.kademi-ci.co/emails/3106799

**Comment by bradmac** [comment]
Found another spot building its own domain name, and changed to use the service

**Comment by bradmac** [comment]
Should be fixed now.

**Comment by Uafinder** [comment]
Yooohooo... finally it's ok!
