### ISSUE TITLE
Deleting points credits fails when there are debits linked to them

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#412]
Eg, in mercedes site, try to delete points for users "ServiceAdvisor SE1" and "PartsManager 1a" fails:

INFO  io.milton.http.HttpManager  - POST :: admin.mercedes.kademi-beta.co///rewards/points/ start
WARN  com.fuselms.apps.learning.LearningApp  - Could not find program for: points - class com.fuselms.apps.learning.rewards.ManagePoints
WARN  com.fuselms.apps.learning.rewards.ManagePoints  - Deleting points: com.fuselms.db.Points@36e742d8
WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 23503
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: update or delete on table "points" violates foreign key constraint "fk_4nijrb2njrbsgvhtks3mj5mwb" on table "points_debit"
  Detail: Key (id)=(47671381) is still referenced from table "points_debit".
ERROR com.fuselms.apps.learning.rewards.ManagePoints  - exception
org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3355)
	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:67)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1130)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1580)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
	at com.fuselms.db.Points.calcPointsBalance(Points.java:493)
	at com.fuselms.db.PointsBalance.calcPointsBalance(PointsBalance.java:119)
	at io.milton.cloud.server.rewards.RewardService.updatePointsBalance(RewardService.java:289)
	at com.fuselms.apps.learning.rewards.ManagePoints.processForm(ManagePoints.java:74)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:49)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:66)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:153)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:219)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "points" violates foreign key constraint "fk_4nijrb2njrbsgvhtks3mj5mwb" on table "points_debit"
  Detail: Key (id)=(47671381) is still referenced from table "points_debit".

**Comment by tuzzmaniandevil** [comment]
Fixed and on Beta/Prod
