### ISSUE TITLE
Update app dependencies error 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4141]
![image](https://user-images.githubusercontent.com/1945230/31438680-c945694a-ae91-11e7-889d-e666c6601117.png)

http://vlad-test13.admin.kademi-ci.co/manageApps/#installed-tab
Manual update is successful
http://vlad-test12.admin.kademi-ci.co/manageApps/#installed-tab
Also the same

**Comment by bradmac** [comment]
@tuzzmaniandevil looks like the same problem you're looking at
```
09:38:22 Caused by: java.lang.NullPointerException
09:38:22 	at io.milton.cloud.server.apps.email.EmailApp.getDependencies(EmailApp.java:1533)
09:38:22 	at io.milton.cloud.server.apps.ApplicationManager.getMissingDepenencies(ApplicationManager.java:1044)
09:38:22 	at io.milton.cloud.server.apps.ApplicationManager.checkAppDependencies(ApplicationManager.java:946)
09:38:22 	at io.milton.cloud.server.apps.ApplicationManager.checkAllDeps(ApplicationManager.java:886)
```

**Comment by tuzzmaniandevil** [comment]
All fixed

**Comment by Uafinder** [comment]
Looks ok!
