### ISSUE TITLE
Can't override uploaded photo in promotion

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4251]
I added `override=true` when upload image in promotion form but I still get error message like:

```
ERROR- io.milton.http.StandardFilter  - exception sending content
java.lang.RuntimeException: Attempt to add duplicate name: 644445_10200673621384724_16889051_n.jpg
	at io.milton.vfs.data.DataSession$DirectoryNode.checkNameForAdd(DataSession.java:518)
	at io.milton.vfs.data.DataSession$DirectoryNode.addFile(DataSession.java:441)
	at io.milton.vfs.data.DataSession$DirectoryNode.addFile(DataSession.java:434)
	at com.fuselms.apps.rewards.RewardUploadsFolder.createNew(RewardUploadsFolder.java:135)
	at io.milton.http.json.PutJsonResource.processFile(PutJsonResource.java:186)
	at io.milton.http.json.PutJsonResource.processForm(PutJsonResource.java:133)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:32)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:187)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bradmac** [comment]
hey @gonzalon just need to update the createNew method to create or replace

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32027431-83d2feee-ba45-11e7-9ef5-b2e17372e431.png)

**Comment by ducdhm** [comment]
Passed!
