### ISSUE TITLE
Error when editing template with non-live version

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4296]
To reproduce go to here and click to a template to edit: http://anh.admin.kademi-ci.co/pages/test2/version2/
Live version is version1 which is working, but not working when in non-live version
```
java.lang.RuntimeException: java.lang.RuntimeException: Attempt to add duplicate name: defaultThemeTemplate.html
	at io.milton.cloud.server.web.templating.TemplateUtils.lambda$editTemplateRedirect$0(TemplateUtils.java:169)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:220)
	at io.milton.cloud.server.web.templating.TemplateUtils.editTemplateRedirect(TemplateUtils.java:144)
	at io.milton.cloud.server.web.templating.TemplateUtils.editTemplateRedirect(TemplateUtils.java:105)
	at io.milton.cloud.server.apps.website.ManageWebsiteBranchFolder.editTemplateRedirect(ManageWebsiteBranchFolder.java:1145)
	at io.milton.cloud.server.apps.website.ManageWebsiteBranchFolder.checkRedirect(ManageWebsiteBranchFolder.java:145)
	at io.milton.http.HandlerHelper.doCheckRedirect(HandlerHelper.java:159)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:161)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:35)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:187)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Attempt to add duplicate name: defaultThemeTemplate.html
	at io.milton.vfs.data.DataSession$DirectoryNode.checkNameForAdd(DataSession.java:518)
	at io.milton.vfs.data.DataSession$DirectoryNode.addFile(DataSession.java:441)
	at io.milton.vfs.data.DataSession$DirectoryNode.addFile(DataSession.java:434)
	at io.milton.cloud.server.web.templating.TemplateUtils.lambda$editTemplateRedirect$0(TemplateUtils.java:162)
	... 26 more

**Comment by bradmac** [comment]
Cant reproduce that problem now, after deleting the template file in the website it seems to work correctly.

However, i've added a check for an existing file so if this happens again it will just redirect without attempting to create
