### ISSUE TITLE
Scheduled email didnt send

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4305]
https://waterco.admin.kademi.com.au/scheduledEmails/adk-test/#configuration-tab

**Comment by bradmac** [comment]
OK, found it
```
java.lang.RuntimeException: java.lang.NullPointerException
	at io.milton.context.RootContext.execute(RootContext.java:93)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.milton.cloud.server.web.WebUtils.getCommonDate(WebUtils.java:816)
	at io.milton.cloud.server.web.WebUtils.getCommonStartDate(WebUtils.java:796)
	at co.kademi.server.query.QueryManager.getCommonStartDate(QueryManager.java:49)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1690$582A$\^eval\_.processModuleActivity(<eval>:94)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1689$254AA$\^eval\_.loadWatercoModuleActivityTable(<eval>:8)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.milton.cloud.server.repoapps.RepoUtils.executeJs(RepoUtils.java:311)
	at co.kademi.server.query.Queries$QueryTable.getRows(Queries.java:155)
	at io.milton.cloud.server.apps.reporting.CustomRepoReportCsvPage.sendAsCsv(CustomRepoReportCsvPage.java:81)
	at io.milton.cloud.server.apps.reporting.CustomRepoReportCsvPage.sendContent(CustomRepoReportCsvPage.java:71)
	at io.milton.cloud.server.apps.scheduler.SchedulerApp$1.beforeSend(SchedulerApp.java:175)
	at io.milton.cloud.server.mail.BatchEmailService.generateHtml(BatchEmailService.java:770)
	at io.milton.cloud.server.mail.BatchEmailService.generateHtml(BatchEmailService.java:728)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$1(BatchEmailService.java:598)
```

**Comment by bradmac** [comment]
The scheduler needs to set the date range into requestcontent attributes, and that needs to be integrated into the accessor methods

**Comment by bradmac** [comment]
Should be fixed now
