### ISSUE TITLE
Accept Task button shows incorrect modal

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4320]
Here : http://alaa-test25.admin.kademi-ci.co/leads/1664667/#tasks-tab when I try to accept the task , it shows me modal with incorrect title "Edit task" and without content

![capture1](https://user-images.githubusercontent.com/26510030/32412573-bc53dce0-c204-11e7-91ef-16ff574c65c7.PNG)

This lead return to this journey : http://alaa-test25.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
Error - "Unable to find resource 'accept'"
```
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'accept'
09:55:15 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
09:55:15 	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
09:55:15 	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1566)
09:55:15 	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:197)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
09:55:15 	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
09:55:15 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
09:55:15 	at org.apache.velocity.Template.merge(Template.java:356)
09:55:15 	at org.apache.velocity.Template.merge(Template.java:260)
09:55:15 	at io.milton.cloud.server.web.templating.VelocityContentDirective.render(VelocityContentDirective.java:65)
09:55:15 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
09:55:15 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
09:55:15 	at org.apache.velocity.Template.merge(Template.java:356)
09:55:15 	at org.apache.velocity.Template.merge(Template.java:260)
09:55:15 	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.lambda$renderHtml$0(HtmlTemplateRenderer.java:207)
09:55:15 	at io.milton.cloud.sec.UntrustedCodeManager.execute(UntrustedCodeManager.java:58)
09:55:15 	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.renderHtml(HtmlTemplateRenderer.java:204)
09:55:15 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:203)
09:55:15 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:122)
09:55:15 	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:41)
09:55:15 	at com.fuselms.apps.leadman.LeadTaskPage.sendContent(LeadTaskPage.java:190)
09:55:15 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
09:55:15 	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
09:55:15 	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
09:55:15 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
```

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 you have specified a task outcome form path here:
![image](https://user-images.githubusercontent.com/826458/32419097-97a29564-c2d9-11e7-9d83-275c2d2804c0.png)

But you havent created a page for it, so there is an error when the server attempts to generate that form

Please just remove the form path unless you want a custom form

**Comment by AlaaKhalaf94** [comment]
Thanks @bradmac , that success with me
