### ISSUE TITLE
Manage leads page bulk deletion doesn't update leads count without refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4349]
1. select some leads by checkboxes
2.  push remove
3. They are still number 3
4. Refresh page and it will be counted correctly.
![image](https://user-images.githubusercontent.com/1945230/32546397-a8c7c47c-c487-11e7-899a-3642881ce4bc.png)
![image](https://user-images.githubusercontent.com/1945230/32546420-b91416c8-c487-11e7-84d2-2362e3f670a1.png)
http://vlad-test36.admin.kademi-ci.co

also, 
it doesn't change stat's on the bottom
it doesn't remove pages which are not needed anymore
it doesn't remove checkbox mark which were used in deletion
![image](https://user-images.githubusercontent.com/1945230/32548999-6e748bc6-c490-11e7-8f5e-d45c48423c41.png)

**Comment by bradmac** [comment]
@anhnt please just remove selected rows with JS

**Comment by anhnt** [comment]
I got error when on leads page

```
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getTotalLeads' in  class com.fuselms.apps.funnels.manage.ManageFunnelLeadsFolder threw exception java.lang.IllegalArgumentException: inner bool query clause cannot be null at rootorg.admin.loopbackdns.com:/theme/apps/funnels/manageFunnelLeads.html[line 2, column 53]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:242)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:292)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:381)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.VelocityContentDirective.render(VelocityContentDirective.java:65)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.lambda$renderHtml$0(HtmlTemplateRenderer.java:207)
	at io.milton.cloud.sec.UntrustedCodeManager.execute(UntrustedCodeManager.java:53)
	at io.milton.cloud.server.web.templating.HtmlTemplateRenderer.renderHtml(HtmlTemplateRenderer.java:204)
	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.writePage(VelocityHtmlTemplater.java:203)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:48)
	at com.fuselms.apps.funnels.manage.ManageFunnelLeadsFolder.sendContent(ManageFunnelLeadsFolder.java:96)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:187)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: inner bool query clause cannot be null
	at org.elasticsearch.index.query.BoolQueryBuilder.must(BoolQueryBuilder.java:114)
	at io.milton.cloud.server.apps.email.EmailResponseEngagementScoringFactorType.appendQuery(EmailResponseEngagementScoringFactorType.java:72)
	at com.fuselms.apps.leadman.LeadmanService.appendRankingFactors(LeadmanService.java:470)
	at com.fuselms.apps.leadman.LeadmanService.lambda$searchLeadsRanked$5(LeadmanService.java:458)
	at io.milton.cloud.server.search.DefaultElasticSearchManager.search(DefaultElasticSearchManager.java:272)
	at io.milton.cloud.server.search.DefaultElasticSearchManager.search(DefaultElasticSearchManager.java:99)
	at io.milton.cloud.server.manager.SearchManager.search(SearchManager.java:850)
	at io.milton.cloud.server.manager.SearchManager.search(SearchManager.java:825)
	at com.fuselms.apps.leadman.LeadmanService.searchLeadsRanked(LeadmanService.java:439)
	at com.fuselms.apps.funnels.manage.ManageFunnelLeadsFolder.lambda$getPaginator$1(ManageFunnelLeadsFolder.java:216)
	at io.milton.cloud.server.web.templating.Paginator2.getRecords(Paginator2.java:56)
	at com.fuselms.apps.funnels.manage.ManageFunnelLeadsFolder.getTotalLeads(ManageFunnelLeadsFolder.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:142)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:543)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:212)
	... 41 more

**Comment by bradmac** [comment]
Fixed error above

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
It works like a charm!
