### ISSUE TITLE
KPI visualization component some options doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4654]
![image](https://user-images.githubusercontent.com/1945230/34097112-8803a8e6-e3e0-11e7-81ef-f0472db9bd43.png)
This options doesn't work
http://version1.vlad06data-vladtest06.kademi-ci.co/rep3.html
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/
http://vladtest06.admin.kademi-ci.co/manageUsers/3353770/#summary-tab

what they should show and what privileges user should have?

**Comment by anhnt** [comment]
Hi @bradmac i fixed the issue with kpiLeaderboard but the issue with pointsLeaderboard and summary. Can you please have a look?

**Comment by anhnt** [comment]
Also when i allocating rewards i got error in console 

![image](https://user-images.githubusercontent.com/735555/34099116-2d7a6f64-e411-11e7-8d2e-6e149566fc81.png)


```
ERROR- io.milton.context.RootContext  - error executing: io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$1454/2115506344@77386f7e
[Error: unresolvable property or identifier: amount]
[Near : {... amount * 10 ....}]
             ^
[Line: 1, Column: 1]
	at org.mvel2.PropertyAccessor.getBeanProperty(PropertyAccessor.java:689)
	at org.mvel2.PropertyAccessor.getNormal(PropertyAccessor.java:178)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:145)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:125)
	at org.mvel2.ast.ASTNode.getReducedValue(ASTNode.java:187)
	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:101)
	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:47)
	at org.mvel2.MVEL.eval(MVEL.java:165)
	at com.fuselms.apps.salesdata.SalesDataApp.evaluatePointsExpr(SalesDataApp.java:1075)
	at com.fuselms.apps.salesdata.SalesDataApp.processKpiPeriodRewards(SalesDataApp.java:654)
	at com.fuselms.apps.salesdata.ManageKpiFolder$SubmitKpiRewardsProcessable.doProcess(ManageKpiFolder.java:596)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$8(LocalAsynchProcessor.java:304)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:94)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:303)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
