### ISSUE TITLE
Delete a product sku code causes the error which doesnt display any SKUs

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4699]
Go to SKUs page, try to delete  a sku text then enter 
Page refreshed and no skus showing

**Comment by bradmac** [comment]
```
16:00:06 Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [co.kademi.db.ProductSku#3698439]
16:00:06 at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:246)
16:00:06 at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:213)
16:00:06 at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:263)
```

**Comment by anhnt** [comment]
Fixed the bug that sends post request 2 times

**Comment by Uafinder** [comment]
Yeah, works great!
