### ISSUE TITLE
Support text assets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4774]
- Ability to add text assets, which are basic media asset types, ie they dont have content fields
- The "text" can be plain text, html or html for email

**Comment by bradmac** [comment]
Done a simple implementation:
![image](https://user-images.githubusercontent.com/826458/34855499-e20a3896-f7a4-11e7-9e02-ac38a9e3bc01.png)

**Comment by bradmac** [comment]
Creating a new text asset, select plain text or html

![image](https://user-images.githubusercontent.com/826458/34855816-a1384b58-f7a6-11e7-8816-bff3dc228ad6.png)

**Comment by bradmac** [comment]
@ducdhm please integrate keditor for format=text/html

![image](https://user-images.githubusercontent.com/826458/34855831-ba8c2016-f7a6-11e7-9711-d546bbc53222.png)

**Comment by bradmac** [comment]
see manageTextAsset.html
```
            #if( $format == "text/html" )
            TODO: use keditor
            <textarea name="text" class="form-control" style="height: 400px">$!page.text</textarea>
            #else
            <textarea name="text" class="form-control" style="height: 400px">$!page.text</textarea>
            #end
```

**Comment by bradmac** [comment]
Added support for Web vs EDM html assets
![image](https://user-images.githubusercontent.com/826458/34856420-da08c0b8-f7a9-11e7-97bb-86527671bb73.png)

And checked that keditor components returns the appropriate handlers. Eg
http://localhost:8080/asset-manager/a034110e-f684-4d44-83b5-b7114571d926/_components?handlers

![image](https://user-images.githubusercontent.com/826458/34856435-f26c9a3a-f7a9-11e7-9545-9e668cd8602a.png)

**Comment by ducdhm** [comment]
@bradmac I got error when saving on this page

```ERROR- org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Value too long for column "TEXT VARCHAR(255)": "STRINGDECODE('<section><div class=\""container-bg background-for\"">\r\n        <div class=\""container-layout\"">\r\n            <d... (1449)"; SQL statement:
insert into base_asset (id, author_profile_id, created_date, format, modified_date, name, notes, tenant_id, unique_id, language, text, type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'T') [90005-144]
ERROR- io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@4216a19f
org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2987)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3499)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:227)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:207)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:191)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:321)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:206)
	at org.hibernate.event.internal.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:55)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:191)
	at org.hibernate.event.internal.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:49)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:683)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at co.kademi.assets.hibernate.HibernateAssetService.createText(HibernateAssetService.java:90)
	at co.kademi.server.content.AssetManager.createTextAsset(AssetManager.java:268)
	at io.milton.cloud.server.apps.content.ManageTextAssetFolder.createOrUpdateItem(ManageTextAssetFolder.java:51)
	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:215)
	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:177)
	at io.milton.cloud.server.apps.content.AbstractManageAssetResource.processForm(AbstractManageAssetResource.java:127)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:191)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "TEXT VARCHAR(255)": "STRINGDECODE('<section><div class=\""container-bg background-for\"">\r\n        <div class=\""container-layout\"">\r\n            <d... (1449)"; SQL statement:
insert into base_asset (id, author_profile_id, created_date, format, modified_date, name, notes, tenant_id, unique_id, language, text, type) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'T') [90005-144]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:316)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:631)
	at org.h2.command.dml.Insert.insertRows(Insert.java:122)
	at org.h2.command.dml.Insert.update(Insert.java:86)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:201)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129)
	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
	... 48 more```

**Comment by bradmac** [comment]
Fixed, after a clean or drop the text column

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
hey @ducdhm ok so we need to either have a preview of the content in the page, or have keditor working inline rather then in a modal.

Please let me know which you prefer, and if you need a hand from me

**Comment by bradmac** [comment]
Actually, now we have related assets being displayed in a modal for relation fields, i think it makes sense to display the editor inline

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Looking good! A couple of things:
- ajax handling of forms needs to be hooked up, but also needs to work in modals
- text inputs should be full width, so lets move the comments section down underneath the main content area
