### ISSUE TITLE
Server error when upload leads on fresh account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4857]
![image](https://user-images.githubusercontent.com/1945230/35439996-1fdb7160-02a6-11e8-96ce-73b5e0df22a7.png)
01:33:58 INFO  org.hibernate.event.internal.DefaultLoadEventListener  - HHH000327: Error performing load command : org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [io.milton.vfs.db.Group#4693367]
01:33:58 ERROR io.milton.http.StandardFilter  - exception sending content
01:33:58 org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [io.milton.vfs.db.Group#4693367]
01:33:58 	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:246)
01:33:58 	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:213)
01:33:58 	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:263)
01:33:58 	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)
01:33:58 	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1017)
01:33:58 	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:944)
01:33:58 	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:671)
01:33:58 	at org.hibernate.type.ManyToOneType.assemble(ManyToOneType.java:282)
01:33:58 	at org.hibernate.collection.internal.PersistentBag.initializeFromCache(PersistentBag.java:160)
01:33:58 	at org.hibernate.cache.spi.entry.CollectionCacheEntry.assemble(CollectionCacheEntry.java:57)
01:33:58 	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.initializeCollectionFromCache(DefaultInitializeCollectionEventListener.java:148)
01:33:58 	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:70)
01:33:58 	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1774)
01:33:58 	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:549)
01:33:58 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:234)
01:33:58 	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545)
01:33:58 	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124)
01:33:58 	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:266)
01:33:58 	at io.milton.vfs.db.Group.findByOrg(Group.java:79)
01:33:58 	at io.milton.vfs.db.Organisation.groups(Organisation.java:821)
01:33:58 	at io.milton.vfs.db.Organisation.group(Organisation.java:803)
01:33:58 	at io.milton.cloud.server.web.KademiSecurityManager.getPriviledges(KademiSecurityManager.java:648)
01:33:58 	at io.milton.cloud.server.web.KademiSecurityManager.authorise(KademiSecurityManager.java:448)
01:33:58 	at io.milton.cloud.server.web.AbstractResource.authorise(AbstractResource.java:158)
01:33:58 	at io.milton.http.HandlerHelper.checkAuthorisation(HandlerHelper.java:148)
01:33:58 	at io.milton.http.HandlerHelper.checkAuthorisation(HandlerHelper.java:127)
01:33:58 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:144)
01:33:58 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
01:33:58 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
01:33:58 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
01:33:58 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
01:33:58 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:33:58 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
01:33:58 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:33:58 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
01:33:58 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:33:58 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
01:33:58 	at io.milton.context.RootContext.execute(RootContext.java:90)
01:33:58 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
01:33:58 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:33:58 	at io.milton.http.HttpManager.process(HttpManager.java:158)
01:33:58 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
01:33:58 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
01:33:58 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
01:33:58 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
01:33:58 	at java.lang.Thread.run(Thread.java:748)

Similar thing was spotted on products uploader.
1. Create fresh account
2. Create a website
3. Install journey app there
4. Edit journeys a bit
5. upload journey leads

[export-leads(13) - Cop1y.zip](https://github.com/Kademi/kademi-dev/files/1667699/export-leads.13.-.Cop1y.zip)
select only emails and name surname and date created

http://vladtest28.admin.kademi-ci.co/tableUploaders/leadsUploader?funnelName=first-journey

**Comment by Uafinder** [comment]
It works!
