### ISSUE TITLE
kfeedback admin page is not openning

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5079]
![image](https://user-images.githubusercontent.com/1945230/36984189-f90f652c-209c-11e8-95cb-d34ccfe589bf.png)
![image](https://user-images.githubusercontent.com/1945230/36984181-f0e4e8ae-209c-11e8-8da0-0a00ad27c8e0.png)
1. I've install learning app, and kfeedbackapp
2. Trying to open kFeedback menu
http://vladtest38e.admin.kademi-ci.co
Fresh account

**Comment by bradmac** [comment]
For some reason the KongoDB dependency isnt being enabled

**Comment by bradmac** [comment]
And thats because there's an init error
```
10:21:38 INFO  io.milton.cloud.server.db.AppControl  - setStatus appId=kfeedbackapp org=vladtest38e enabled=true controlId=8149987
10:21:38 INFO  io.milton.cloud.server.apps.ApplicationManager  - checkAppDependencies: is dependent app.
10:21:38 INFO  io.milton.cloud.server.apps.ApplicationManager  - No app dependencies for repo app kfeedbackapp version=io.milton.vfs.db.Branch@d6321a1
10:21:38 INFO  io.milton.cloud.server.repoapps.ControllerMappingList  - executeFunction: executing..
10:21:38 INFO  KodeJS  - initApp Kfeedback: orgRoot=io.milton.cloud.server.apps.orgs.OrganisationRootFolder@4e3c5201
10:21:39 ERROR io.milton.cloud.server.repoapps.RepositoryApp  - Exception initialisaing app: kfeedbackapp because ReferenceError: "page" is not defined in /APP-INF/app.js at line number 110
10:21:39 javax.script.ScriptException: ReferenceError: "page" is not defined in /APP-INF/app.js at line number 110
10:21:39 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
10:21:39 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
10:21:39 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
10:21:39 	at io.milton.cloud.server.repoapps.ControllerMappingList.call(ControllerMappingList.java:1111)
10:21:39 	at io.milton.cloud.server.repoapps.RepositoryApp.initApp(RepositoryApp.java:542)
10:21:39 	at io.milton.cloud.server.apps.ApplicationManager.enable(ApplicationManager.java:960)
10:21:39 	at io.milton.cloud.server.apps.ApplicationManager.setStatus(ApplicationManager.java:886)
10:21:39 	at io.milton.cloud.server.apps.website.AppsPageHelper.setStatus(AppsPageHelper.java:191)
10:21:39 	at io.milton.cloud.server.apps.website.AppsPageHelper.updateApplicationEnabled(AppsPageHelper.java:106)
10:21:39 	at io.milton.cloud.server.apps.admin.ManageAppsPage.appId(ManageAppsPage.java:96)
10:21:39 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:215)
10:21:39 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:177)
10:21:39 	at io.milton.cloud.server.apps.admin.ManageAppsPage.processForm(ManageAppsPage.java:76)
10:21:39 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
10:21:39 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
10:21:39 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
10:21:39 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
10:21:39 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
10:21:39 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
10:21:39 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:39 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
10:21:39 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:39 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
10:21:39 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:39 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
10:21:39 	at io.milton.context.RootContext.execute(RootContext.java:90)
10:21:39 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
10:21:39 	at io.milton.http.FilterChain.process(FilterChain.java:46)
10:21:39 	at io.milton.http.HttpManager.process(HttpManager.java:158)
10:21:39 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
10:21:39 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
10:21:39 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
10:21:39 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
10:21:39 	at java.lang.Thread.run(Thread.java:748)
10:21:39 Caused by: /APP-INF/app.js:110 ReferenceError: "page" is not defined
10:21:39 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
10:21:39 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
10:21:39 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
10:21:39 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
10:21:39 	at jdk.nashorn.internal.scripts.Script$Recompilation$2835$2970AAA$\^eval\_.initApp(/APP-INF/app.js:110)
10:21:39 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:643)
10:21:39 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
10:21:39 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
10:21:39 	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
10:21:39 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
```

**Comment by bradmac** [comment]
Eek ... this is just crazy
```
function initApp(orgRoot, webRoot, enabled) {
    log.info("initApp Kfeedback: orgRoot={}", orgRoot);
    
    var dbs = orgRoot.find(JSON_DB);
    if (isNull(dbs)) {
        page.throwNotFound('KongoDB is disabled. Please enable it for continue with this app!');
        return;
    }
```

**Comment by bradmac** [comment]
OK, this is the problem:
```
10:21:38 INFO  io.milton.cloud.server.apps.ApplicationManager  - No app dependencies for repo app kfeedbackapp
```

Looks like the deps.json file is in the wrong folder, so the dependencies arent being found

**Comment by bradmac** [comment]
Looks better..
```
10:39:17 INFO  io.milton.cloud.server.apps.website.AppsPageHelper  - setStatus: kfeedbackapp = true org=io.milton.vfs.db.Organisation@7c4d90 website=null
10:39:17 INFO  io.milton.cloud.server.apps.ApplicationManager  - App kfeedbackapp of type class io.milton.cloud.server.repoapps.RepositoryApp is already installed. Will enable it
10:39:17 INFO  io.milton.cloud.server.db.AppControl  - setStatus appId=kfeedbackapp org=vladtest38e enabled=true controlId=8149987
10:39:17 INFO  io.milton.cloud.server.apps.ApplicationManager  - checkAppDependencies: is dependent app.
10:39:17 INFO  io.milton.cloud.server.apps.ApplicationManager  - getMissingDepenencies: Found 1 deps for app kfeedbackapp
10:39:17 INFO  io.milton.cloud.server.apps.ApplicationManager  - Installed app: KongoDB
```

**Comment by bradmac** [comment]
And that page is displaying now
![image](https://user-images.githubusercontent.com/826458/37001249-c60ad984-212a-11e8-96eb-d51e9c7c6e45.png)

**Comment by Uafinder** [comment]
Yup, looks fine
