### ISSUE TITLE
Update ecom store to support variants and inventory control

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5174]
- add to cart button should just link to the product details page
- on the product detail page, the add to cart section should display variants same as for reward store.

See rewardProductCartButtonComponent.html

**Comment by bradmac** [comment]
Seeing a NPE
```
INFO - io.milton.http.HttpManager  - POST :: ecom1-rootorg.loopbackdns.com:8080///storeCheckout start
ERROR- io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@25617ca4
java.lang.NullPointerException
	at com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.addOrUpdateShoppingCartItem(ECommerceShoppingCartResource.java:540)
	at com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.doAddItemHref(ECommerceShoppingCartResource.java:120)
	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:215)
	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:177)
	at com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.processForm(ECommerceShoppingCartResource.java:97)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
```

**Comment by bradmac** [comment]
@tuzzmaniandevil please get the functionality working. Anh can assist if needed

**Comment by anhnt** [comment]
I can see products with variants are being added to cart with correct hrefs but title doesnt seems to show

```
#foreach( $opt in $item.itemPage.optionTitles( $item.selectedParameterOptions ).entrySet() )
                            <br />
                            <small class="text-muted">
                                $opt.key: $opt.value
                            </small>
                            #end

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/37884883-ab7f34cc-310e-11e8-9385-ecadf27a1dee.png)

looking better now

**Comment by anhnt** [comment]
Checked out and submitted orders which have variants successfully. 
@Uafinder please ping me when you test this i will show you eway app settings

**Comment by Uafinder** [comment]
1. Additional backslash in product details link
![image](https://user-images.githubusercontent.com/1945230/37906051-915bdfb4-3109-11e8-93c8-9aeda562c7ee.png)
http://vladtest46web-vladtest46.kademi-ci.co/vladtest46web-ecomstore//p1/

2. 404 error while click add to cart button
![image](https://user-images.githubusercontent.com/1945230/37906101-b4d185fc-3109-11e8-86ef-aa298f6a7d5a.png)
http://vladtest46web-vladtest46.kademi-ci.co/vladtest46web-ecomstore/13423093/?param-memory=16gb&param-color=blk

http://vladtest46.admin.kademi-ci.co/ecommerce/vladtest46web-ecomstore/#products-tab

**Comment by anhnt** [comment]
@bradmac i cant add item to cart.
http://version1.w1-anhtest35.kademi-ci.co/w1-ecomstore/p2/?param-color=Gold
An ajax request to http://version1.w1-anhtest35.kademi-ci.co/w1-ecomstore/13660615/?param-color=Gold&getOrderForm saying 404 not found

**Comment by anhnt** [comment]
```
class java.lang.NullPointerException::null
- com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.addOrUpdateShoppingCartItem(ECommerceShoppingCartResource.java:540)
- com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.doAddItemHref(ECommerceShoppingCartResource.java:120)
- io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:215)
- io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:177)
- com.fuselms.apps.ecommerce.ECommerceShoppingCartResource.processForm(ECommerceShoppingCartResource.java:97)
- io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
- io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
- io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
- io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
- io.milton.http.http11.PostHandler.process(PostHandler.java:62)
- io.milton.http.StandardFilter.process(StandardFilter.java:50)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
- io.milton.context.RootContext.execute(RootContext.java:90)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.http.HttpManager.process(HttpManager.java:158)
- co.kademi.server.Kademi$1.service(Kademi.java:194)
- org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
- java.lang.Thread.run(Thread.java:748)

```
Form data: 
addItemHref: ?param-color=Grey
addItemQuantity: 1

**Comment by anhnt** [comment]
Still cant add item to cart with this form data:

addItemHref: /vladtest46web-ecomstore/p1/?param-memory=16gb&param-color=blk
addItemQuantity: 1

http://version1.vladtest46web-vladtest46.kademi-ci.co/vladtest46web-ecomstore/p1/?param-color=blk&param-memory=16gb

There is no error in the log

**Comment by anhnt** [comment]
JSON response:

{"data":null,"fieldMessages":[],"messages":["Added item /vladtest46web-ecomstore/p1/?param-memory=16gb&param-color=blk"],"nextHref":"","status":true}

**Comment by bradmac** [comment]
I'm seeing this exception
```
16:44:34 INFO  io.milton.http.HttpManager  - POST :: version1.vladtest46web-vladtest46.kademi-ci.co///storeCheckout start
16:44:34 ERROR co.kademi.server.stream.StreamManager  - Exception logging event to the stream: io.milton.cloud.server.event.ShoppingCartEvent@135e1b2b because: null
16:44:34 java.lang.NullPointerException
16:44:34 	at io.milton.cloud.server.event.ShoppingCartEvent.getUser(ShoppingCartEvent.java:353)
16:44:34 	at co.kademi.server.stream.StreamManager$StreamEventListenever.onEvent(StreamManager.java:104)
16:44:34 	at io.milton.event.EventManagerImpl.fireEvent(EventManagerImpl.java:42)
16:44:34 	at io.milton.cloud.util.EventUtils.fireQuietly(EventUtils.java:35)
```

**Comment by bradmac** [comment]
Fixed a few problems with href handling. Should work now.

@Uafinder please try again

**Comment by bradmac** [comment]
Required ecommerce-lib 1.1.6

**Comment by anhnt** [comment]
1 & 2 fixed

**Comment by Uafinder** [comment]
Both ok...
Same with image
![image](https://user-images.githubusercontent.com/1945230/39182258-fa481ad4-47c4-11e8-82b8-18ca0e5f711e.png)
http://vladtest49uestore-vladtest49u.kademi-ci.co/storeCheckout/

On the checkout page - it using image which are from product details, not from variants.

**Comment by anhnt** [comment]
@bradmac please have a look. I got NPE when seeing ecom product detail page

```
ERROR- io.milton.cloud.server.apps.ComponentBean  - Exception executing component: ecomProduct cause: Invocation of method 'getPurchaseAmount' in  class com.fuselms.apps.ecommerce.ProductInECommerceStoreResource threw exception java.lang.NullPointerException at w1-gfgfg_rootorg.loopbackdns.com:/theme/apps/ecommerce/components/ecomProductComponent.html[line 61, column 42]
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getPurchaseAmount' in  class com.fuselms.apps.ecommerce.ProductInECommerceStoreResource threw exception java.lang.NullPointerException at w1-gfgfg_rootorg.loopbackdns.com:/theme/apps/ecommerce/components/ecomProductComponent.html[line 61, column 42]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:258)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:213)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:292)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:579)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.TextTemplater.lambda$writePage$3(TextTemplater.java:176)
	at io.milton.cloud.sec.UntrustedCodeManager.execute(UntrustedCodeManager.java:53)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:174)
	at io.milton.cloud.server.apps.ComponentBean.renderComponent(ComponentBean.java:228)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:208)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:120)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:220)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:120)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:101)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:92)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater._writePage(ComponentHtmlTemplater.java:258)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.lambda$writePage$1(ComponentHtmlTemplater.java:158)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:156)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:136)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:41)
	at com.fuselms.apps.ecommerce.ProductInECommerceStoreResource.sendContent(ProductInECommerceStoreResource.java:140)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:194)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.fuselms.apps.ecommerce.PricingRulesService$PricingRulesSet.access$900(PricingRulesService.java:254)
	at com.fuselms.apps.ecommerce.PricingRulesService.findMatching(PricingRulesService.java:172)
	at com.fuselms.apps.ecommerce.PricingRulesService.applyRules(PricingRulesService.java:160)
	at com.fuselms.apps.ecommerce.PriceManager.finalCost(PriceManager.java:60)
	at com.fuselms.apps.ecommerce.PriceManager.finalCost(PriceManager.java:53)
	at com.fuselms.apps.ecommerce.ProductInECommerceStoreResource.getPurchaseAmount(ProductInECommerceStoreResource.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:399)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:388)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:192)
	... 53 more

**Comment by bradmac** [comment]
I think its a problem when the rules are retrieved from the cache. Pushed a change that i think will fix it.

**Comment by bradmac** [comment]
But leave this with me, i want to refactor how ecom handles variants to use SKU id's instead of the list of selectioned options

**Comment by bradmac** [comment]
Closing because this is redundant now - https://github.com/Kademi/kademi-dev/issues/5450
