### ISSUE TITLE
Exception generating kcrm timeline

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5200]
http://kcrm.kademi.us/leads/21011624/

```
INFO - 26-03-2018T03:14:57,131 - io.milton.http.HttpManager  - GET :: www.kademi.co///theme/images/preloader-dark@2x.gif finished 171ms, Status:HTTP/1.1 200 OK, Length:4770
INFO - 26-03-2018T03:15:03,183 - io.milton.http.HttpManager  - GET :: kcrm.kademi.us///leads/21011624/ start
WARN - 26-03-2018T03:15:03,190 - org.hibernate.engine.internal.StatefulPersistenceContext  - HHH000179: Narrowing proxy to class io.milton.vfs.db.Organisation - this operation breaks ==
INFO - 26-03-2018T03:15:03,220 - io.milton.cloud.server.apps.user.UserApp  - Time is not elapsed
WARN - 26-03-2018T03:15:03,227 - org.hibernate.engine.internal.StatefulPersistenceContext  - HHH000179: Narrowing proxy to class io.milton.vfs.db.Website - this operation breaks ==
WARN - 26-03-2018T03:15:03,227 - org.hibernate.engine.internal.StatefulPersistenceContext  - HHH000179: Narrowing proxy to class io.milton.vfs.db.Website - this operation breaks ==
INFO - 26-03-2018T03:15:03,234 - KodeJS  - getGooglemapPortlet > page=[object Array], params={}, context={}
INFO - 26-03-2018T03:15:03,245 - KodeJS  - getLeadmanOrgSelector
ERROR- 26-03-2018T03:15:03,317 - io.milton.cloud.server.apps.ComponentBean  - Exception executing component: leadTimeline cause: Invocation of method 'getTimelineItems' in  class com.fuselms.apps.leadman.LeadPage threw exception java.lang.IllegalArgumentException: Comparison method violates its general contract! at /theme/apps/leadman/leadManTimeline.html[line 1, column 21]
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getTimelineItems' in  class com.fuselms.apps.leadman.LeadPage threw exception java.lang.IllegalArgumentException: Comparison method violates its general contract! at /theme/apps/leadman/leadManTimeline.html[line 1, column 21]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:242)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:292)
	at org.apache.velocity.context.ProxyVMContext.get(ProxyVMContext.java:219)
	at org.apache.velocity.runtime.parser.node.ASTReference.getVariableValue(ASTReference.java:1003)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:240)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:579)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:318)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at io.milton.cloud.server.web.templating.TextTemplater.lambda$writePage$3(TextTemplater.java:176)
	at io.milton.cloud.sec.UntrustedCodeManager.execute(UntrustedCodeManager.java:58)
	at io.milton.cloud.server.web.templating.TextTemplater.writePage(TextTemplater.java:174)
	at io.milton.cloud.server.apps.ComponentBean.renderComponent(ComponentBean.java:228)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:196)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:117)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:208)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:117)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:98)
	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:89)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater._writePage(ComponentHtmlTemplater.java:258)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.lambda$writePage$1(ComponentHtmlTemplater.java:158)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:156)
	at io.milton.cloud.server.web.templating.ComponentHtmlTemplater.writePage(ComponentHtmlTemplater.java:136)
	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.writePage(ThemeDependentHtmlTemplater.java:41)
	at com.fuselms.apps.leadman.LeadPage.sendContent(LeadPage.java:751)
	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at co.kademi.server.Kademi$1.service(Kademi.java:194)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1460)
	at java.util.Collections.sort(Collections.java:175)
	at com.fuselms.apps.leadman.LeadPage.lambda$getTimelineItems$6(LeadPage.java:1153)
	at io.milton.cloud.server.db.utils.LazyValueHolder2.get(LazyValueHolder2.java:39)
	at com.fuselms.apps.leadman.LeadPage.getTimelineItems(LeadPage.java:1130)
	at sun.reflect.GeneratedMethodAccessor1080.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:142)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:543)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:212)
	... 60 more

```

**Comment by gonzalon** [comment]
This should be fixed we need to deploy
