### ISSUE TITLE
Exception adding attachments and starting journsy from batch emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5252]
```
	... 4 more
Caused by: org.hibernate.SessionException: Session is closed!
	at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:130)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:48)
	at io.milton.cloud.server.mail.GroupEmailService$2.addAttachments(GroupEmailService.java:417)
	at io.milton.cloud.server.mail.BatchEmailService.addAnyAttachments(BatchEmailService.java:944)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$167(BatchEmailService.java:628)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.mail.BatchEmailService.enqueueSingleEmail(BatchEmailService.java:617)
	at io.milton.cloud.server.mail.BatchEmailService.generateEmailItems(BatchEmailService.java:294)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:378)
	... 11 more
INFO - 29-03-2018T19:53:21,342 - io.milton.cloud.server.db.EmailTrigger  - find triggers: eventId=goal
INFO - 29-03-2018T19:53:21,342 - io.milton.cloud.server.db.EmailTrigger  - find: event=goal org=rhipe list size=0 in time=0ms
INFO - 29-03-2018T19:53:21,343 - io.milton.cloud.server.apps.email.EmailApp  - onEvent: TriggerEvent: class com.fuselms.apps.funnels.GoalAttainedTriggerEvent processed in 1ms
INFO - 29-03-2018T19:53:21,346 - co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=899447742 updates=1 creates=0 loads=1
ERROR- 29-03-2018T19:53:21,346 - io.milton.context.RootContext  - error executing: io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer$$Lambda$1683/213935270@5c4d6779
java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:380)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:261)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$164(BatchEmailService.java:376)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$165(BatchEmailService.java:375)
	at io.milton.cloud.util.SessionManagerUtils.executeInSession(SessionManagerUtils.java:59)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$run$166(BatchEmailService.java:367)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.run(BatchEmailService.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.SessionException: Session is closed!
	at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:130)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:48)
	at io.milton.cloud.server.mail.GroupEmailService$2.addAttachments(GroupEmailService.java:417)
	at io.milton.cloud.server.mail.BatchEmailService.addAnyAttachments(BatchEmailService.java:944)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$167(BatchEmailService.java:628)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.mail.BatchEmailService.enqueueSingleEmail(BatchEmailService.java:617)
	at io.milton.cloud.server.mail.BatchEmailService.generateEmailItems(BatchEmailService.java:294)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:378)
	... 11 more
ERROR- 29-03-2018T19:53:21,346 - io.milton.cloud.server.mail.BatchEmailService  - Exception occurred processing batch 113145386
java.lang.RuntimeException: java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.context.RootContext.execute(RootContext.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.run(BatchEmailService.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:380)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:261)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$164(BatchEmailService.java:376)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$165(BatchEmailService.java:375)
	at io.milton.cloud.util.SessionManagerUtils.executeInSession(SessionManagerUtils.java:59)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$run$166(BatchEmailService.java:367)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	... 4 more
Caused by: org.hibernate.SessionException: Session is closed!
	at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:130)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:48)
	at io.milton.cloud.server.mail.GroupEmailService$2.addAttachments(GroupEmailService.java:417)
	at io.milton.cloud.server.mail.BatchEmailService.addAnyAttachments(BatchEmailService.java:944)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$167(BatchEmailService.java:628)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.mail.BatchEmailService.enqueueSingleEmail(BatchEmailService.java:617)
	at io.milton.cloud.server.mail.BatchEmailService.generateEmailItems(BatchEmailService.java:294)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:378)
	... 11 more
INFO - 29-03-2018T19:53:21,356 - io.milton.cloud.server.db.EmailTrigger  - find triggers: eventId=goal
INFO - 29-03-2018T19:53:21,356 - io.milton.cloud.server.db.EmailTrigger  - find: event=goal org=rhipe list size=0 in time=0ms
INFO - 29-03-2018T19:53:21,356 - io.milton.cloud.server.apps.email.EmailApp  - onEvent: TriggerEvent: class com.fuselms.apps.funnels.GoalAttainedTriggerEvent processed in 0ms
INFO - 29-03-2018T19:53:21,357 - io.milton.cloud.server.db.EmailTrigger  - find triggers: eventId=goal
INFO - 29-03-2018T19:53:21,358 - io.milton.cloud.server.db.EmailTrigger  - find: event=goal org=rhipe list size=0 in time=1ms
INFO - 29-03-2018T19:53:21,358 - io.milton.cloud.server.apps.email.EmailApp  - onEvent: TriggerEvent: class com.fuselms.apps.funnels.GoalAttainedTriggerEvent processed in 1ms
INFO - 29-03-2018T19:53:21,358 - co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=341022654 updates=1 creates=0 loads=1
ERROR- 29-03-2018T19:53:21,358 - io.milton.context.RootContext  - error executing: io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer$$Lambda$1683/213935270@28bfbc6
java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:380)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:261)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$164(BatchEmailService.java:376)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$165(BatchEmailService.java:375)
	at io.milton.cloud.util.SessionManagerUtils.executeInSession(SessionManagerUtils.java:59)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$run$166(BatchEmailService.java:367)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.run(BatchEmailService.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.SessionException: Session is closed!
	at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:130)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:48)
	at io.milton.cloud.server.mail.GroupEmailService$2.addAttachments(GroupEmailService.java:417)
	at io.milton.cloud.server.mail.BatchEmailService.addAnyAttachments(BatchEmailService.java:944)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$167(BatchEmailService.java:628)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.mail.BatchEmailService.enqueueSingleEmail(BatchEmailService.java:617)
	at io.milton.cloud.server.mail.BatchEmailService.generateEmailItems(BatchEmailService.java:294)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:378)
	... 11 more
ERROR- 29-03-2018T19:53:21,359 - io.milton.cloud.server.mail.BatchEmailService  - Exception occurred processing batch 113145386
java.lang.RuntimeException: java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.context.RootContext.execute(RootContext.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.run(BatchEmailService.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.hibernate.SessionException: Session is closed!
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:380)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:261)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$164(BatchEmailService.java:376)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$165(BatchEmailService.java:375)
	at io.milton.cloud.util.SessionManagerUtils.executeInSession(SessionManagerUtils.java:59)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$run$166(BatchEmailService.java:367)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	... 4 more
Caused by: org.hibernate.SessionException: Session is closed!
	at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:130)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:675)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:48)
	at io.milton.cloud.server.mail.GroupEmailService$2.addAttachments(GroupEmailService.java:417)
	at io.milton.cloud.server.mail.BatchEmailService.addAnyAttachments(BatchEmailService.java:944)
	at io.milton.cloud.server.mail.BatchEmailService.lambda$enqueueSingleEmail$167(BatchEmailService.java:628)
	at co.kademi.server.experiments.ExperimentsService.doInTestContext(ExperimentsService.java:112)
	at io.milton.cloud.server.mail.BatchEmailService.enqueueSingleEmail(BatchEmailService.java:617)
	at io.milton.cloud.server.mail.BatchEmailService.generateEmailItems(BatchEmailService.java:294)
	at io.milton.cloud.server.mail.BatchEmailService$SendBatchQueueConsumer.lambda$null$163(BatchEmailService.java:378)
	... 11 more

```

**Comment by bradmac** [comment]
Also..
```
	at java.util.TimerThread.run(Timer.java:505)
WARN - 29-03-2018T19:45:12,581 - org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 23503
ERROR- 29-03-2018T19:45:12,581 - org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: insert or update on table "funnel_edm" violates foreign key constraint "fk_q0mggwo5x1kccwmuuvai3fqr1"
  Detail: Key (email_item)=(113151827) is not present in table "email_item".
ERROR- 29-03-2018T19:45:12,581 - com.fuselms.apps.funnels.FunnelApp  - ScanLeadTimersProcess: Exception occurred prcessing trigger timers
org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:301)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
	at com.fuselms.apps.funnels.FunnelApp$ScanLeadTimersProcess._doProcess(FunnelApp.java:602)
	at com.fuselms.apps.funnels.FunnelApp$ScanLeadTimersProcess.doProcess(FunnelApp.java:544)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:308)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$1.run(LocalAsynchProcessor.java:95)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "funnel_edm" violates foreign key constraint "fk_q0mggwo5x1kccwmuuvai3fqr1"
  Detail: Key (email_item)=(113151827) is not present in table "email_item".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)

```

**Comment by bradmac** [comment]
@Uafinder I've pushed a fix, but can you please do a test of 1000 emails in QA to check?

Please check
- using the start journey option
- and adding an attachment

**Comment by Uafinder** [comment]
yup, looks fine for me
