### ISSUE TITLE
exception in xero

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5329]
```
14:35:13 ERROR io.milton.context.RootContext  - error executing: io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$720/1252011474@17f017aa
14:35:13 com.xero.api.XeroApiException: token_rejected - Token 8QUZVDGF6WW5Z6AAUJZ1MJY8EBMCTK does not match an expected ACCESS token 
14:35:13 	at com.xero.api.exception.XeroExceptionHandler.newApiException(XeroExceptionHandler.java:136)
14:35:13 	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:99)
14:35:13 	at com.xero.api.XeroClient.get(XeroClient.java:211)
14:35:13 	at com.xero.api.XeroClient.getContacts(XeroClient.java:668)
14:35:13 	at co.kademi.server.apps.xero.XeroService.getContactByContactNumber(XeroService.java:190)
14:35:13 	at co.kademi.server.apps.xero.XeroService.getOrCreateContact(XeroService.java:415)
14:35:13 	at co.kademi.server.apps.xero.XeroService.generateInvoice(XeroService.java:350)
14:35:13 	at co.kademi.server.apps.xero.XeroService.createInvoicesFromHolders(XeroService.java:234)
14:35:13 	at co.kademi.server.apps.xero.XeroApp.createInvoice(XeroApp.java:117)
14:35:13 	at io.milton.cloud.server.apps.invoicing.InvoicingService.createInvoices(InvoicingService.java:81)
14:35:13 	at io.milton.cloud.server.apps.invoicing.InvoicingService.processOrg(InvoicingService.java:293)
14:35:13 	at com.fuselms.apps.rewardstore.InvoicingProcessor.lambda$null$0(InvoicingProcessor.java:53)
14:35:13 	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:98)
14:35:13 	at com.fuselms.apps.rewardstore.InvoicingProcessor.lambda$doProcess$1(InvoicingProcessor.java:52)
14:35:13 	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:266)
14:35:13 	at com.fuselms.apps.rewardstore.InvoicingProcessor.doProcess(InvoicingProcessor.java:51)
14:35:13 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:308)
14:35:13 	at io.milton.context.RootContext.execute(RootContext.java:90)
14:35:13 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
14:35:13 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
14:35:13 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$1.run(LocalAsynchProcessor.java:95)
14:35:13 	at java.util.TimerThread.mainLoop(Timer.java:555)
14:35:13 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by bradmac** [comment]
duplicate of https://github.com/Kademi/kademi-dev/issues/5343
