### ISSUE TITLE
Upgrade base recognition to have an associated asset

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5642]
Just like products, badges, levels, ... etc should have an associated asset, in case there's a need to create a description page for a badge, or extra paragraphs like how to earn, we currently need that for Vayability

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
Sorry i didnt get time to do this today.

What i think you should do is 
- create a new admin mapping for levels and badges
- move editing functions to those pages (but leave creation where it is)
- add the asset linking to the detail pages, so it will be same as for products and categories (ie not use modals)

I think we need this because there will be additional management functions to add to badges and levels which will need their own page anyway, and this means we can be consistent with products/categories.

**Comment by mkhoudary** [comment]
Updated badges and added edit pages, made asset edit exactly like products/categories, what's left now is same for levels.

@bradmac I didn't remove edit functionality from first screen as some users might just need a badge with name/title/image, are you sure you want me to remove the edit functionality?

**Comment by mkhoudary** [comment]
Added edit function for badges, also assets are edited/added same way as for products, also added edit functionality. What's left is applying same to levels.

@bradmac it's sometimes good to have edit/image upload features on the go (in the topic page) are you sure I shall remove the modify feature from the topic page?

**Comment by bradmac** [comment]
@mkhoudary if you're happy I'm happy :)

**Comment by mkhoudary** [comment]
I am happy :-)

**Comment by mkhoudary** [comment]
@Uafinder please give this a test.. currently badges are working which is what we need for Vayability.. I created another issue for levels

**Comment by Uafinder** [comment]
Image uploading for badge now failed
![image](https://user-images.githubusercontent.com/1945230/42822265-497110e2-89e3-11e8-89d7-a94772878c54.png)
17:02:54 ERROR io.milton.http.StandardFilter  - exception sending content
17:02:54 java.lang.NullPointerException
17:02:54 	at org.hibernate.proxy.HibernateProxyHelper.getClassWithoutInitializingProxy(HibernateProxyHelper.java:47)
17:02:54 	at io.milton.cloud.server.repoapps.ControllerResource.dataBind(ControllerResource.java:563)
17:02:54 	at jdk.nashorn.internal.scripts.Script$Recompilation$53893$3222$\^eval\_.L:3#_uploadBadgeImage#L:96(/APP-INF/admin/manageBadge.js:102)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
17:02:54 	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
17:02:54 	at io.milton.cloud.server.repoapps.ControllerMappingList.executeJs(ControllerMappingList.java:1247)
17:02:54 	at io.milton.cloud.server.repoapps.AppTransactionManager.lambda$runInTransaction$0(AppTransactionManager.java:91)
17:02:54 	at io.milton.cloud.util.SessionManagerUtils.lambda$executeInSessionAndTransaction$0(SessionManagerUtils.java:118)
17:02:54 	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:248)
17:02:54 	at io.milton.cloud.util.SessionManagerUtils.produceInSessionAndTransaction(SessionManagerUtils.java:131)
17:02:54 	at io.milton.cloud.util.SessionManagerUtils.executeInSessionAndTransaction(SessionManagerUtils.java:117)
17:02:54 	at io.milton.cloud.server.repoapps.AppTransactionManager.runInTransaction(AppTransactionManager.java:89)
17:02:54 	at jdk.nashorn.internal.scripts.Script$Recompilation$53892$2998AAA$\^eval\_.L:3#_uploadBadgeImage(/APP-INF/admin/manageBadge.js:96)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:643)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
17:02:54 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
17:02:54 	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
17:02:54 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
17:02:54 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
17:02:54 	at io.milton.cloud.server.repoapps.ControllerResource.executeJs(ControllerResource.java:321)
17:02:54 	at io.milton.cloud.server.repoapps.ControllerResource.processForm(ControllerResource.java:167)
17:02:54 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
17:02:54 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
17:02:54 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
17:02:54 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
17:02:54 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
17:02:54 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
17:02:54 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:02:54 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
17:02:54 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:02:54 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
17:02:54 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:02:54 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
17:02:54 	at io.milton.context.RootContext.execute(RootContext.java:90)
17:02:54 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
17:02:54 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:02:54 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
17:02:54 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:02:54 	at io.milton.http.HttpManager.process(HttpManager.java:158)
17:02:54 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
17:02:54 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
17:02:54 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
17:02:54 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
17:02:54 	at java.lang.Thread.run(Thread.java:748)

http://vladtest53f.admin.kademi-ci.co/recognition/17079452/
