### ISSUE TITLE
EDM journey node error while send test

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5676]
![image](https://user-images.githubusercontent.com/1945230/42698314-3b9a39a0-86c6-11e8-87fb-48a4fa7045e7.png)
http://vladtest53d.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-525880/#summary-tab
Seems like it wants to have lead specified, but that's not correct.

error log
```
17:56:51 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: insert or update on table "funnel_edm" violates foreign key constraint "fk_d3t7hh5auj30v6sxdtebv1mb2"
17:56:51   Detail: Key (lead)=(0) is not present in table "lead".
17:56:51 ERROR com.fuselms.apps.funnels.manage.ManageSendEmailResource  - Couldnt send test email
17:56:51 org.hibernate.exception.ConstraintViolationException: could not execute statement
17:56:51 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
17:56:51 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
17:56:51 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
17:56:51 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
17:56:51 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
17:56:51 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58)
17:56:51 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079)
17:56:51 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521)
17:56:51 	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88)
17:56:51 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
17:56:51 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
17:56:51 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:301)
17:56:51 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
17:56:51 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
17:56:51 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
17:56:51 	at io.milton.cloud.server.db.FunnelEdm.create(FunnelEdm.java:50)
17:56:51 	at com.fuselms.apps.funnels.SendEmailGoalAction.generateEmail(SendEmailGoalAction.java:353)
17:56:51 	at com.fuselms.apps.funnels.SendEmailGoalAction.send(SendEmailGoalAction.java:214)
17:56:51 	at com.fuselms.apps.funnels.manage.ManageSendEmailResource.sendTest(ManageSendEmailResource.java:326)
17:56:51 	at com.fuselms.apps.funnels.manage.ManageSendEmailResource.lambda$processForm$1(ManageSendEmailResource.java:127)
17:56:51 	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:278)
17:56:51 	at com.fuselms.apps.funnels.manage.ManageSendEmailResource.processForm(ManageSendEmailResource.java:125)
17:56:51 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
17:56:51 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
17:56:51 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
17:56:51 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
17:56:51 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
17:56:51 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
17:56:51 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:56:51 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
17:56:51 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:56:51 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
17:56:51 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:56:51 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
17:56:51 	at io.milton.context.RootContext.execute(RootContext.java:90)
17:56:51 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
17:56:51 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:56:51 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
17:56:51 	at io.milton.http.FilterChain.process(FilterChain.java:46)
17:56:51 	at io.milton.http.HttpManager.process(HttpManager.java:158)
17:56:51 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
17:56:51 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
17:56:51 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
17:56:51 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
17:56:51 	at java.lang.Thread.run(Thread.java:748)
17:56:51 Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "funnel_edm" violates foreign key constraint "fk_d3t7hh5auj30v6sxdtebv1mb2"
17:56:51   Detail: Key (lead)=(0) is not present in table "lead".
17:56:51 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
17:56:51 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
17:56:51 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
17:56:51 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
17:56:51 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
17:56:51 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
17:56:51 	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
17:56:51 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
17:56:51 	... 40 more
17:56:51 ERROR co.kademi.server.logging.KademiSimpleJdbcEventListener  - SQL Exception: insert into funnel_edm (email_item, funnel, lead, node_id, originating_org, sms_item, id) values (17018218, 17003903, 0, 'initialGoalTestName', 17003446, NULL, 17018219)
```

**Comment by bradmac** [comment]
```
17:56:51 Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "funnel_edm" violates foreign key constraint "fk_d3t7hh5auj30v6sxdtebv1mb2"
17:56:51   Detail: Key (lead)=(0) is not present in table "lead".
```

**Comment by bradmac** [comment]
Added code to not create a link to a lead when the lead is jsut a fake testing one.

Should be fixed now

**Comment by Uafinder** [comment]
Ok, it works by initially pressing button, but when you using send test to mechanism it fails with error:
![image](https://user-images.githubusercontent.com/1945230/42744852-0c2471c2-88d8-11e8-85b7-a9e63a42ffaf.png)
http://vladtest53e.admin.kademi-ci.co/funnels/first-journey/version1/email1/#summary-tab
![image](https://user-images.githubusercontent.com/1945230/42744857-178f0eaa-88d8-11e8-92ed-42300f9b5db5.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good now
