### ISSUE TITLE
SalesClaim App: Error saving from non-OCR claim form

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5731]
```
Caused by: java.lang.IllegalArgumentException: Invalid format: ""
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parse(DateFieldMapper.java:243)
	at org.elasticsearch.index.mapper.DateFieldMapper.parseCreateField(DateFieldMapper.java:468)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:287)
	... 36 more
```
From this form
![image](https://user-images.githubusercontent.com/826458/43057850-a3200670-8e98-11e8-9473-d983a527f67a.png)

**Comment by bradmac** [comment]
Related https://github.com/Kademi/kademi-dev/issues/5673#event-1746650327

**Comment by bradmac** [comment]
Seems to be that soldDate is an empty string in the json passed to addOrUpdateItem

**Comment by tuzzmaniandevil** [comment]
What form is that from?

**Comment by bradmac** [comment]
Running locally, using this as the test page..

```
<html>
	<head>
		<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
		<title>Home</title>
		<link rel="template" href="theme/home" />
		<script type="data/parameter" title="itemType" ></script>
		<script type="data/parameter" title="category" ></script>
		<script type="data/parameter" title="tags" ></script>
	</head>
	<body>
		<section>
			<div class="container-bg background-for">
				<div class="container-layout">
					<div class="container-content-wrapper">
						<div class="row">
							<div class="col-sm-6" data-type="container-content">
								<section class="" data-type="component-salesDataImageClaimerForm">
									<div data-dynamic-href="_components/salesDataImageClaimerForm" id="keditor-dynamic-element-1532318231712"></div>
								</section>
							</div>
							<div class="col-sm-6" data-type="container-content">
								<section class="" data-type="component-claimForm">
									<div data-dynamic-href="_components/claimForm" id="keditor-dynamic-element-1532318253583"></div>
								</section>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</body>
</html>

```

**Comment by bradmac** [comment]
If its working for you, then maybe deploy the app to CI and setup an account we can both see?

**Comment by bradmac** [comment]
FYI, still seeing that error..

**Comment by bradmac** [comment]
Looks good now
