### ISSUE TITLE
Error submitting OCR claim

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5732]
Related: https://github.com/Kademi/kademi-dev/issues/5673#event-1746650327
```
Caused by: /APP-INF/app.js:319 ReferenceError: "isNumber" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3065$12852A$\^eval\_.getAutoRejectThreshold(/APP-INF/app.js:319)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3064$15044AA$\^eval\_.handleScanJobEvent(/APP-INF/app.js:380)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
	... 22 more
```

This is from the OCR claims form:
![image](https://user-images.githubusercontent.com/826458/43058051-95625c1c-8e99-11e8-8cef-517ec9f3b62b.png)

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-dev/pull/5735
