### ISSUE TITLE
KCRM: Companies list page - delete problem

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5890]
(from https://github.com/Kademi/kademi-dev/issues/5847)

4. Reproduced error for deletion company, company has assigned member (membership not null). Message should appear or error should be fixed.

```
14:59:28 ERROR co.kademi.server.logging.KademiSimpleJdbcEventListener  - SQL Exception: delete from org_entity where id=17746737
14:59:28 WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 23503
14:59:28 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_j4ldk8unv1bajr5kn2812ircp" on table "group_membership"
14:59:28   Detail: Key (id)=(17746737) is still referenced from table "group_membership".
14:59:28 INFO  co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=539249037 updates=1 creates=0 loads=0
14:59:28 ERROR io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@2bea34be
14:59:28 org.hibernate.exception.ConstraintViolationException: could not execute statement
14:59:28 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
14:59:28 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
14:59:28 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
14:59:28 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
14:59:28 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
14:59:28 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3358)
14:59:28 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
14:59:28 	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
14:59:28 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
14:59:28 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
14:59:28 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
14:59:28 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
14:59:28 	at com.fuselms.apps.leadman.LeadmanService.deleteLeadCompany(LeadmanService.java:728)
14:59:28 	at com.fuselms.apps.leadman.LeadCompaniesFolder.deleteCompanies(LeadCompaniesFolder.java:83)
14:59:28 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:228)
14:59:28 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:189)
14:59:28 	at com.fuselms.apps.leadman.LeadCompaniesFolder.processForm(LeadCompaniesFolder.java:69)
14:59:28 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
14:59:28 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
14:59:28 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
14:59:28 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
14:59:28 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
14:59:28 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
14:59:28 	at io.milton.context.RootContext.execute(RootContext.java:90)
14:59:28 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
14:59:28 	at io.milton.http.FilterChain.process(FilterChain.java:46)
14:59:28 	at io.milton.http.HttpManager.process(HttpManager.java:158)
14:59:28 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
14:59:28 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
14:59:28 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
14:59:28 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
14:59:28 	at java.lang.Thread.run(Thread.java:748)
14:59:28 Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_j4ldk8unv1bajr5kn2812ircp" on table "group_membership"
14:59:28   Detail: Key (id)=(17746737) is still referenced from table "group_membership".
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
14:59:28 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
14:59:28 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
14:59:28 	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
14:59:28 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
14:59:28 	... 37 more
```

**Comment by Uafinder** [comment]
Well, error looks now different
11:32:45 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_2dkcsoqdj6sqr0qtp7bs0t6hi" on table "signup_log"
11:32:45   Detail: Key (id)=(17759262) is still referenced from table "signup_log".
11:32:45 ERROR io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@4dd344f5
11:32:45 org.hibernate.exception.ConstraintViolationException: could not execute statement
11:32:45 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
11:32:45 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
11:32:45 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
11:32:45 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
11:32:45 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
11:32:45 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3358)
11:32:45 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3558)
11:32:45 	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:102)
11:32:45 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
11:32:45 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
11:32:45 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:308)
11:32:45 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
11:32:45 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
11:32:45 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
11:32:45 	at com.fuselms.apps.leadman.LeadmanService.deleteLeadCompany(LeadmanService.java:732)
11:32:45 	at com.fuselms.apps.leadman.LeadCompaniesFolder.deleteCompanies(LeadCompaniesFolder.java:83)
11:32:45 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:228)
11:32:45 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:189)
11:32:45 	at com.fuselms.apps.leadman.LeadCompaniesFolder.processForm(LeadCompaniesFolder.java:69)
11:32:45 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
11:32:45 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
11:32:45 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
11:32:45 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
11:32:45 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
11:32:45 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
11:32:45 	at io.milton.http.FilterChain.process(FilterChain.java:46)
11:32:45 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
11:32:45 	at io.milton.http.FilterChain.process(FilterChain.java:46)
11:32:45 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
11:32:45 	at io.milton.http.FilterChain.process(FilterChain.java:46)
11:32:45 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
11:32:45 	at io.milton.context.RootContext.execute(RootContext.java:90)
11:32:45 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
11:32:45 	at io.milton.http.FilterChain.process(FilterChain.java:46)
11:32:45 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
11:32:45 	at io.milton.http.FilterChain.process(FilterChain.java:46)
11:32:45 	at io.milton.http.HttpManager.process(HttpManager.java:158)
11:32:45 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
11:32:45 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
11:32:45 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
11:32:45 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
11:32:45 	at java.lang.Thread.run(Thread.java:748)
11:32:45 Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "org_entity" violates foreign key constraint "fk_2dkcsoqdj6sqr0qtp7bs0t6hi" on table "signup_log"
11:32:45   Detail: Key (id)=(17759262) is still referenced from table "signup_log".
11:32:45 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
11:32:45 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
11:32:45 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
11:32:45 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
11:32:45 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
11:32:45 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
11:32:45 	at com.p6spy.engine.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:95)
11:32:45 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)

Tried to delete company 4
http://vladtest53tweb-vladtest53t.kademi-ci.co/companies/
user kcrmadmin

**Comment by bradmac** [comment]
I think its ok to move this to the backlog
