### ISSUE TITLE
Integration processes fail when events are fired and clearsession is true

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6030]
```
EXCEPTION: at Row 2095 : org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session: 
java.lang.RuntimeException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session
	at io.milton.vfs.db.Profile.getOrCreateGroupMembership(Profile.java:737)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:117)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:112)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:108)
	at io.milton.cloud.server.web.OrgData.createMembership(OrgData.java:873)
	at io.milton.cloud.server.web.OrgData.createMembership(OrgData.java:836)
	at jdk.nashorn.internal.scripts.Script$Recompilation$46309$4257AAAAAAAAAAAAAAAAA$\^eval\_.processNightlyAccounts(/integration/js/integration.js:171)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:651)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at co.kademi.server.integration.impl.JsRowStep.exec(JsRowStep.java:116)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:147)
	at co.kademi.server.integration.impl.CsvInput.exec(CsvInput.java:148)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:147)
	at co.kademi.server.integration.impl.TransactionStep.exec(TransactionStep.java:115)
	at co.kademi.server.integration.Pipeline.start(Pipeline.java:235)
	at com.fuselms.apps.integration.IntegrationService.triggerInboundPipeline(IntegrationService.java:253)
	at com.fuselms.apps.integration.PipelineScheduleProcessable.lambda$doProcess$0(PipelineScheduleProcessable.java:62)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:99)
	at com.fuselms.apps.integration.PipelineScheduleProcessable.doProcess(PipelineScheduleProcessable.java:53)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$8(LocalAsynchProcessor.java:304)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:99)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:303)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124)
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:266)
	at io.milton.vfs.db.Repository.branch(Repository.java:258)
	at io.milton.vfs.db.Repository.liveBranch(Repository.java:268)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.getWebsiteRootFolder(DefaultCurrentRootFolderService.java:205)
	at io.milton.cloud.server.repoapps.RepoAppsEventManager.onEvent(RepoAppsEventManager.java:63)
	at io.milton.cloud.server.event.KademiEventManagerImpl.fireEvent(KademiEventManagerImpl.java:62)
	at io.milton.cloud.util.EventUtils.fireQuietly(EventUtils.java:35)
	at io.milton.cloud.server.manager.GroupManager.lambda$getOrCreateGroupMembership$0(GroupManager.java:132)
	at io.milton.vfs.db.Profile.getOrCreateGroupMembership(Profile.java:735)
	... 35 more
```

**Comment by bradmac** [comment]
Error is from trying to get enabled apps for the contextual website

**Comment by bradmac** [comment]
Similar..

```
EXCEPTION: at Row 260 : org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session: 
java.lang.RuntimeException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session
	at io.milton.vfs.db.Profile.getOrCreateGroupMembership(Profile.java:737)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:117)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:112)
	at io.milton.cloud.server.manager.GroupManager.getOrCreateGroupMembership(GroupManager.java:108)
	at io.milton.cloud.server.web.OrgData.createMembership(OrgData.java:876)
	at io.milton.cloud.server.web.OrgData.createMembership(OrgData.java:838)
	at jdk.nashorn.internal.scripts.Script$Recompilation$23828$4257AAAAAAAAAAAAAAAAA$\^eval\_.processNightlyAccounts(/integration/js/integration.js:171)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:651)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at co.kademi.server.integration.impl.JsRowStep.exec(JsRowStep.java:116)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:147)
	at co.kademi.server.integration.impl.CsvInput.exec(CsvInput.java:148)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:147)
	at co.kademi.server.integration.impl.TransactionStep.exec(TransactionStep.java:115)
	at co.kademi.server.integration.Pipeline.start(Pipeline.java:235)
	at com.fuselms.apps.integration.IntegrationService.triggerInboundPipeline(IntegrationService.java:253)
	at com.fuselms.apps.integration.PipelineScheduleProcessable.lambda$doProcess$365(PipelineScheduleProcessable.java:62)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:99)
	at com.fuselms.apps.integration.PipelineScheduleProcessable.doProcess(PipelineScheduleProcessable.java:53)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$1463(LocalAsynchProcessor.java:304)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:99)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$1464(LocalAsynchProcessor.java:303)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.milton.vfs.db.Repository.branches, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:566)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:186)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:545)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:124)
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:266)
	at io.milton.vfs.db.Repository.branch(Repository.java:258)
	at io.milton.vfs.db.Repository.liveBranch(Repository.java:268)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.getWebsiteRootFolder(DefaultCurrentRootFolderService.java:205)
	at io.milton.cloud.server.repoapps.RepoAppsEventManager.onEvent(RepoAppsEventManager.java:63)
	at io.milton.cloud.server.event.KademiEventManagerImpl.fireEvent(KademiEventManagerImpl.java:62)
	at io.milton.cloud.util.EventUtils.fireQuietly(EventUtils.java:35)
	at io.milton.cloud.server.manager.GroupManager.lambda$getOrCreateGroupMembership$28(GroupManager.java:132)
	at io.milton.vfs.db.Profile.getOrCreateGroupMembership(Profile.java:735)
	... 35 more
```

**Comment by bradmac** [comment]
OK, trying a different approach. Now we're selectively clearing only certain classes from the session.

That should avoid having objects needed for overall state (eg website, admin org) becoming invalid
