### ISSUE TITLE
Promotion issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6152]
Could not save it
![image](https://user-images.githubusercontent.com/1945230/46875768-445fe280-ce45-11e8-8b9d-9ba69b1f2f7b.png)
http://vladtest54b.admin.kademi-ci.co/rewards/promo-123/#details-tab

**Comment by bradmac** [comment]
I was able to save it.

What fields did you enter?

**Comment by Uafinder** [comment]
reproduced

13:33:32 ERROR co.kademi.server.logging.KademiSimpleJdbcEventListener  - SQL Exception: insert into repository (base_entity, created_date, deleted, live_branch, name, notes, public_content, title, type, id) values (18188956, '15-Nov-18', NULL, 'version1', 'rewards', NULL, false, 'rewards', NULL, 18189733)
13:33:32 WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 23505
13:33:32 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: duplicate key value violates unique constraint "uk_be4aqqgtkwgc9sl8tvbpp61yc"
13:33:32   Detail: Key (name, base_entity)=(rewards, 18188956) already exists.
13:33:32 ERROR io.milton.vfs.content.DbHashStore  - Exception inserting hash=e372e14b5d820ac101d5f0f28262b5a075615de5 type='c' into FanoutHash
13:33:32 org.hibernate.exception.ConstraintViolationException: could not execute statement
13:33:32 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
13:33:32 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
13:33:32 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
13:33:32 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
13:33:32 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
13:33:32 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58)
13:33:32 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079)
13:33:32 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521)
13:33:32 	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88)
13:33:32 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:393)
13:33:32 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:385)
13:33:32 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:301)
13:33:32 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
13:33:32 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
13:33:32 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159)
13:33:32 	at io.milton.vfs.db.FanoutHash.insertFanout(FanoutHash.java:48)
13:33:32 	at io.milton.vfs.content.DbHashStore.setChunkFanout(DbHashStore.java:30)
13:33:32 	at io.milton.sync.SessionPerRequestHashStore.lambda$setChunkFanout$0(SessionPerRequestHashStore.java:41)
13:33:32 	at io.milton.cloud.util.SessionManagerUtils.executeInSession(SessionManagerUtils.java:52)
13:33:32 	at io.milton.sync.SessionPerRequestHashStore.setChunkFanout(SessionPerRequestHashStore.java:40)
13:33:32 	at org.hashsplit4j.store.CachingHashStore.setChunkFanout(CachingHashStore.java:31)
13:33:32 	at org.hashsplit4j.api.Parser.parse(Parser.java:172)
13:33:32 	at io.milton.vfs.data.DataSession$FileNode.setContent(DataSession.java:541)
13:33:32 	at com.fuselms.apps.rewards.RewardFolder.saveRewardProps(RewardFolder.java:174)
13:33:32 	at com.fuselms.apps.rewards.ManageRewardFolder.saveProps(ManageRewardFolder.java:242)
13:33:32 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:228)
13:33:32 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:189)
13:33:32 	at com.fuselms.apps.rewards.ManageRewardFolder.processForm(ManageRewardFolder.java:115)
13:33:32 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
13:33:32 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
13:33:32 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
13:33:32 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
13:33:32 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
13:33:32 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
13:33:32 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:33:32 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
13:33:32 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:33:32 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
13:33:32 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:33:32 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
13:33:32 	at io.milton.context.RootContext.execute(RootContext.java:90)
13:33:32 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
13:33:32 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:33:32 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
13:33:32 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:33:32 	at io.milton.http.HttpManager.process(HttpManager.java:158)
13:33:32 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
13:33:32 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
13:33:32 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
13:33:32 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
13:33:32 	at java.lang.Thread.run(Thread.java:748)
13:33:32 Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_be4aqqgtkwgc9sl8tvbpp61yc"
13:33:32   Detail: Key (name, base_entity)=(rewards, 18188956) already exists.

![image](https://user-images.githubusercontent.com/1945230/48480149-1f7ad880-e812-11e8-93ff-021a9d346e66.png)
http://vladtest54tt.admin.kademi-ci.co/rewards/prmotopn1/#details-tab
