### ISSUE TITLE
Hinda API: shipping status isnt working

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6360]

**Comment by bradmac** [comment]
Just checked, and that order status hasnt changed yet (on hindas side)

**Comment by bradmac** [comment]
Looks ok to me..

![image](https://user-images.githubusercontent.com/826458/49983209-1eca9300-ffc6-11e8-902d-d54bc3c8ee26.png)

**Comment by bradmac** [comment]
Related:

https://github.com/Kademi/kademi-dev/issues/6430

**Comment by bradmac** [comment]
Need to set tracking information into ProductOrder and Cart to work with 6430

**Comment by bradmac** [comment]
Updated as per michael's request.

**Comment by bradmac** [comment]
Mostly working but...
```
INFO - 19-12-2018T01:50:06,526 - co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=1284688000 updates=174 creates=0 loads=73
ERROR- 19-12-2018T01:50:06,526 - co.kademi.processors.OrderStatusProcessor  - doProcess: Error trying to update the orders.
java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at co.kademi.processors.OrderStatusProcessor.addIfMissing(OrderStatusProcessor.java:139)
	at co.kademi.processors.OrderStatusProcessor.updateOrder(OrderStatusProcessor.java:257)
	at co.kademi.processors.OrderStatusProcessor.lambda$_doProcess$0(OrderStatusProcessor.java:110)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:283)
	at co.kademi.processors.OrderStatusProcessor._doProcess(OrderStatusProcessor.java:109)
	at co.kademi.processors.OrderStatusProcessor.doProcess(OrderStatusProcessor.java:59)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$null$8(LocalAsynchProcessor.java:304)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:104)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:303)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$QueueProcessor.run(LocalAsynchProcessor.java:259)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by bradmac** [comment]
Patched into beta .. its processed a bnuch of orders, although many processed are still in the incomplete state

Here's one that was marked as complete

https://owenscorningbrookville.admin.kademi.us/shopping-carts/65241894/

**Comment by bradmac** [comment]
This will be applied to other servers in the next deploy
