### ISSUE TITLE
order doesn't change status to Fullfilment complete

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6398]
![image](https://user-images.githubusercontent.com/1945230/49651277-68036b80-fa37-11e8-96b0-f2077bf5d56c.png)
http://vladtest55f.admin.kademi-ci.co/shopping-carts/18309896/

**Comment by bradmac** [comment]
Due to this error:

```
08:17:09 java.lang.NullPointerException
08:17:09 	at com.fuselms.apps.funnels.OrderStatusGoal.matches(OrderStatusGoal.java:64)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.findMatchingBeginNodeForAutomation(FunnelManager.java:1308)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.checkFunnel(FunnelManager.java:535)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.lambda$null$1(FunnelManager.java:451)
08:17:09 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
08:17:09 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.lambda$onFunnelEvent$2(FunnelManager.java:444)
08:17:09 	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:274)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.onFunnelEvent(FunnelManager.java:434)
08:17:09 	at com.fuselms.apps.funnels.FunnelManager.onEvent(FunnelManager.java:283)
08:17:09 	at io.milton.cloud.server.event.KademiEventManagerImpl.fireEvent(KademiEventManagerImpl.java:62)
08:17:09 	at io.milton.cloud.util.EventUtils.fireQuietly(EventUtils.java:35)
08:17:09 	at co.kademi.server.catalog.CartManager.setFulfillmentStatus(CartManager.java:160)
08:17:09 	at com.fuselms.apps.shoppingcart.ManageShoppingCartFolder.setStatus(ManageShoppingCartFolder.java:68)
```

**Comment by bradmac** [comment]
Fixed the NPE in OrderStatusGoal, and also now displays the error if one occurs

**Comment by Uafinder** [comment]
looks good
