### ISSUE TITLE
BCC failing on KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6496]
This lead http://kcrm-kademi.kademi.us/leads/65220931/

This is the mail system at host mailout.west.internal.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

**Comment by bradmac** [comment]
Sorry, what happened?

**Comment by paddyow** [comment]
When I send an email and BCC using the KCRM email capture address, I get a bounce back to my email client for every lead.

**Comment by bradmac** [comment]
```
INFO - 11-01-2019T01:56:01,922 - io.milton.cloud.server.mail.MiltonCloudMailResourceFactory  - getMailbox: to-lead-65220931@kcrm-kademi.kademi.us
WARN - 11-01-2019T01:56:01,939 - io.milton.cloud.server.repoapps.RepoUtils  - Could not find file: /WEB-INF/controllers.xml
WARN - 11-01-2019T01:56:01,940 - io.milton.cloud.server.repoapps.ControllerMappingList  - Parsed JS in 1 ms
ERROR- 11-01-2019T01:56:01,947 - io.milton.cloud.server.apps.email.MCMailFilter  - Exception executing mail filterio.milton.mail.FilterChain@4494717b
java.lang.NullPointerException
	at io.milton.cloud.server.web.templating.Formatter.isSecure(Formatter.java:2846)
	at io.milton.cloud.server.apps.website.WebsiteRootFolder.externalUrl(WebsiteRootFolder.java:348)
	at io.milton.cloud.server.apps.website.WebsiteRootFolder.getExternalUrl(WebsiteRootFolder.java:330)
	at io.milton.cloud.server.apps.ApplicationManager.geActiveEmailApps(ApplicationManager.java:647)
	at io.milton.cloud.server.apps.ApplicationManager.getMailbox(ApplicationManager.java:619)
	at io.milton.cloud.server.mail.MiltonCloudMailResourceFactory.getMailbox(MiltonCloudMailResourceFactory.java:40)
	at io.milton.mail.receive.SubethaSmtpServer$1.doEvent(SubethaSmtpServer.java:119)
	at io.milton.mail.FilterChain.doEvent(FilterChain.java:56)
	at io.milton.cloud.server.apps.email.MCMailFilter.lambda$doEvent$0(MCMailFilter.java:51)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.apps.email.MCMailFilter.doEvent(MCMailFilter.java:47)
	at io.milton.mail.FilterChain.doEvent(FilterChain.java:50)
	at io.milton.mail.receive.SubethaSmtpServer.accept(SubethaSmtpServer.java:127)
	at org.subethamail.smtp.server.MessageListenerAdapter$Handler.recipient(MessageListenerAdapter.java:147)
	at org.subethamail.smtp.command.ReceiptCommand.execute(ReceiptCommand.java:52)
	at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:58)
	at org.subethamail.smtp.server.ConnectionHandler.run(ConnectionHandler.java:113)

```

**Comment by bradmac** [comment]
I'll test once deployed to prod
