### ISSUE TITLE
SMS not sending (Minda)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6673]
I'm seeing that SMS not sending and not sure why
http://minda.admin.kademi.com.au/smsHistory/
Could you check it pls?
![image](https://user-images.githubusercontent.com/1945230/52328640-f9239e00-29f8-11e9-829c-144859e61fde.png)
http://minda.admin.kademi.com.au/smsHistory/140404759

**Comment by bradmac** [comment]
```
ERROR- 08-02-2019T13:23:20,711 - co.kademi.server.sms.SmsItemQueueStore  - checkForGroupSmsJob: Exception processing SMS items
java.lang.RuntimeException: Failed to send message 140461172
	at co.kademi.server.sms.clicksend.ClickSendApp.sendSms(ClickSendApp.java:224)
	at co.kademi.server.sms.SmsApp.sendSms(SmsApp.java:428)
	at co.kademi.server.sms.SmsItemQueueStore.next(SmsItemQueueStore.java:186)
	at co.kademi.server.sms.SmsItemQueueStore.doProcess(SmsItemQueueStore.java:50)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:308)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$1.run(LocalAsynchProcessor.java:95)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

``

**Comment by bradmac** [comment]
this error:
```
SMS SEND CLICKSEND-HTTP URL [ https://api.clicksend.com/rest/v2/send.xml?method=rest&to=0423945687&message=Colleen%E2%80%99s+son+Jerome+loved+painting+at+Minda.+She+shares+memories+of+him+here+http%3A%2F%2Fbit.ly%2F2kCNdH1.+Thank+you+for+being+behind+families+like+these%21 ] -- response [ Authorisation Failed ] 
```

"Authorisation Failed"

**Comment by bradmac** [comment]
I've pushed a fix to capture the error message and update SMS status to "Failed".

**Comment by Uafinder** [comment]
Ok, looks better
