### ISSUE TITLE
NPE error when profile contains extra field for groups and it's empty (non-mandatory)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6688]
![image](https://user-images.githubusercontent.com/1945230/52473105-a8997580-2b9d-11e9-9a62-7bce0ff29e2a.png)
http://vladtest56mmm.admin.kademi-ci.co/manageUsers/18757618/#general-tab
http://vladtest56mmm.admin.kademi-ci.co/groups/18757130/

**Comment by bradmac** [comment]
```
08:42:26 ERROR io.milton.cloud.util.SessionManagerUtils  - Exception processing: command io.milton.cloud.util.Command@739e7bcb
08:42:26 java.lang.RuntimeException: Couldnt find group: null
08:42:26 	at io.milton.cloud.server.manager.GroupManager.setExtraFieldGroup(GroupManager.java:902)
08:42:26 	at io.milton.cloud.server.manager.GroupManager.storeExtraFields(GroupManager.java:616)
08:42:26 	at io.milton.cloud.server.apps.admin.ManageUserPage.updateProfile(ManageUserPage.java:579)
08:42:26 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:232)
08:42:26 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:193)
08:42:26 	at io.milton.cloud.server.apps.admin.ManageUserPage.processForm(ManageUserPage.java:188)
```

**Comment by bradmac** [comment]
Fixed. Requires platform update.

**Comment by Uafinder** [comment]
Looks good now
