### ISSUE TITLE
Backup is not working

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6788]
It is not working  on current CI ie http://moblix.admin.kademi-ci.co/backup/ but seems ok on new QA server

**Comment by anhnt** [comment]
i can see this locally too

```
ERROR- io.milton.context.RootContext  - error executing: io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$1487/1393804829@51d6aa75
java.lang.StackOverflowError
	at org.apache.log4j.helpers.PatternConverter.spacePad(PatternConverter.java:107)
	at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:80)
	at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.info(Log4jLoggerAdapter.java:323)
	at io.milton.cloud.server.apps.BackupableApplication.toMap(BackupableApplication.java:118)
	at io.milton.cloud.server.apps.BackupableApplication.addList(BackupableApplication.java:94)
	at io.milton.cloud.server.apps.BackupableApplication.toMap(BackupableApplication.java:143)
	at io.milton.cloud.server.apps.BackupableApplication.toMap(BackupableApplication.java:159)
	at io.milton.cloud.server.apps.BackupableApplication.addList(BackupableApplication.java:94)
	at io.milton.cloud.server.apps.BackupableApplication.toMap(BackupableApplication.java:143)
	at io.milton.cloud.server.apps.BackupableApplication.toMap(BackupableApplication.java:159)

**Comment by bradmac** [comment]
Worked ok for me locally, so must be a data issue

I've added a defensive check to prevent stackoverflows from recursive calls

**Comment by Uafinder** [comment]
Still looks bad on moblix server
![image](https://user-images.githubusercontent.com/1945230/53411815-3368d580-39d0-11e9-96aa-dc7015440393.png)

**Comment by bradmac** [comment]
pushed a couple of fixes

**Comment by Uafinder** [comment]
Looks good now
