### ISSUE TITLE
DbAsyncProcessor: Transaction handling

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6904]
Processors which define their own transaction handling currently fail, because DbAsyncProcessor is wrapping the entire process with a transaction:

```
EXCEPTION : nested transactions not supported: 
org.hibernate.TransactionException: nested transactions not supported
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:152)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1351)
	at co.kademi.server.integration.impl.TransactionStep.exec(TransactionStep.java:73)
	at co.kademi.server.integration.Pipeline.exec(Pipeline.java:162)
	at co.kademi.server.integration.impl.MultiStep._exec(MultiStep.java:61)
	at co.kademi.server.integration.impl.MultiStep.exec(MultiStep.java:47)
	at co.kademi.server.integration.Pipeline.start(Pipeline.java:251)
	at com.fuselms.apps.integration.UploadPipelineProcessable.lambda$doProcess$0(UploadPipelineProcessable.java:161)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:107)
	at com.fuselms.apps.integration.UploadPipelineProcessable.doProcess(UploadPipelineProcessable.java:135)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor.lambda$null$8(DbAsyncProcessor.java:392)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:303)
	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:262)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor.lambda$null$9(DbAsyncProcessor.java:386)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:107)
	at io.milton.cloud.server.manager.DefaultCurrentRootFolderService.doWithCurrent(DefaultCurrentRootFolderService.java:93)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor.lambda$runJob$11(DbAsyncProcessor.java:385)
	at io.milton.cloud.util.SessionManagerUtils.executeInSessionNoTx(SessionManagerUtils.java:88)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor.runJob(DbAsyncProcessor.java:337)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor.access$700(DbAsyncProcessor.java:45)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor$QueueProcessor.lambda$run$0(DbAsyncProcessor.java:541)
	at io.milton.context.RootContext.execute(RootContext.java:90)
	at io.milton.cloud.server.queue.impl.DbAsyncProcessor$QueueProcessor.run(DbAsyncProcessor.java:540)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bradmac** [comment]
I think CancellableTrackedProcessable needs a property to specify whether to wrap with a transaction

If not wrapping, then DbAsyncProcessor should just use a local transaction when updating job status.

**Comment by bradmac** [comment]
Should be fixed in UploadPipelineProcessable now
