### ISSUE TITLE
Cannot duplicate email

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#820]
Title: 2nd Launch Registration eDM
name: 2nd-launch-registration-edm

java.lang.NumberFormatException: For input string: "edm"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.milton.cloud.server.web.WebUtils.incrementFileName(WebUtils.java:832)
	at io.milton.cloud.server.apps.email.ManageGroupEmailFolder.duplicateSendJob(ManageGroupEmailFolder.java:630)

**Comment by bradmac** [comment]
Please first create a unit test to reproduce the error. Then update the function to fix the error, and leave the unit test
